import 'reflect-metadata';
import dotenv from 'dotenv';
import { DataSource } from 'typeorm';
import {
  AuthSession,
  Notification,
  NotificationPreference,
  Organization,
  OrganizationMembership,
  OrganizationSecurityPolicy,
  OrganizationSettings,
  MfaRateLimit,
  Program,
  User,
  UserIdentity,
  Affiliate,
  AffiliatePortalProfile,
  AffiliateTaxCertificate,
  AffiliatePayoutMethod,
  AffiliateSupportTicket,
  AffiliateInvitation,
  ProgramAffiliate,
  AffiliateApplication,
  TrackingLink,
  Click,
  Attribution,
  ApiKey,
  IdempotencyKey,
  Conversion,
  CommissionRule,
  Commission,
  LedgerAccount,
  LedgerTransaction,
  LedgerEntry,
  FraudReview,
  FraudSettings,
  FraudAssessment,
  FraudSignal,
  AffiliateTrustHistory,
  FraudMetricRollup,
  FraudRule,
  FraudRuleVersion,
  FraudAlert,
  FraudInvestigation,
  FraudHold,
  FraudException,
  PayoutBatch,
  PayoutItem,
  WebhookEndpoint,
  WebhookDelivery,
  AuditLog,
  DemoBooking,
  GoogleCalendarConnection,
  PublicKey,
  UserDevice,
  UserMfaConfig,
  UserRecoveryCode,
  MfaChallenge,
  AuthSecurityEvent,
  Integration,
  OrganizationIntegration,
  IntegrationCredential,
  IntegrationEvent,
  IntegrationOAuthState,
  IntegrationPlatformConfig,
  CrmPipelineMapping,
  CrmFieldMapping,
  CrmEntityMapping,
  IntegrationSyncLog,
  PartnerDeal,
  OrganizationTrial,
  BillingAccount,
  UserLegalAcceptance,
  BillingPlan,
  BillingPlanProviderMapping,
  BillingPlanFeature,
  BillingPlanLimit,
  BillingAddon,
  BillingAddonPurchase,
  BillingPromotion,
  BillingCoupon,
  BillingCouponPlan,
  BillingCouponOrganization,
  BillingCouponRedemption,
  BillingSubscriptionDiscount,
  OrganizationCoupon,
  OrganizationCouponAssignment,
  OrganizationCouponSettings,
  BillingSubscription,
  BillingPayment,
  BillingPaymentEvent,
  BillingRefund,
  BillingInvoice,
  Asset,
  AssetVersion,
  AssetBundle,
  AssetBundleItem,
  AssetTag,
  AffiliateAssetActivity,
  AffiliateAssetFavorite,
  PartnerTier,
  AffiliateTier,
  AffiliateTierHistory,
  Milestone,
  AffiliateMilestoneAchievement,
  AffiliatePerformanceSummary,
  AutomationWorkflow,
  AutomationWorkflowVersion,
  AutomationExecution,
  AutomationScheduledStep,
  AutomationEmailTemplate,
  EmailDesignTemplate,
  EmailDesignSettings,
  OrganizationBranding,
  DocumentDesignTemplate,
  DocumentTemplateVersion,
  GeneratedDocument,
  AutomationEmailLog,
  EmailTemplateVersion,
  EmailTemplateOverride,
  EmailDeliveryLog,
  EmailSuppression,
  PlatformSetting,
  BlogPost,
  SecurityEvent,
  SecuritySignal,
  SecurityAlert,
  SecurityInvestigation,
  SecurityIncident,
  SecurityRule,
  SecurityRuleVersion,
  SecurityAction,
  SecurityException,
  ApiRequest,
  ApiExternalCall,
  ApiErrorGroup,
  ApiRateLimitQuota,
  ApiActivityAudit,
  ApiActivityException,
  WebhookEndpointRecord,
  WebhookEventRecord,
  WebhookDeliveryRecord,
  WebhookDeliveryAttemptRecord,
  WebhookEventTypeDefinition,
  WebhookDeadLetterRecord,
  WebhookSecurityIncidentRecord,
  WebhookExceptionRecord,
  WebhookAuditRecord,
  SystemMonitoredService,
  SystemHealthCheckResult,
  SystemIncident,
  SystemServiceDependency,
  SystemDeploymentRecord,
  SystemMaintenanceWindow,
  FeatureFlag,
  FeatureFlagEnvironment,
  FeatureFlagRule,
  FeatureFlagOverride,
  FeatureFlagVersion,
  FeatureFlagDependency,
  FeatureFlagEvaluationMetric,
  FeatureFlagSettingsRecord,
} from './schema';
import {
  RoleDefinition,
  PermissionDefinition,
  RolePermission,
  OrganizationPolicy,
  OrganizationInvitation,
} from './schema-rbac';
import {
  GovernancePolicy,
  GovernancePolicyVersion,
  GovernanceApprovalPolicy,
  GovernanceApprovalRequest,
  GovernanceException,
  GovernanceEmergencyControl,
  GovernanceViolation,
} from './schema-governance';

export function isTestRun(): boolean {
  if (process.env.NODE_ENV === 'test') return true;
  if (Boolean(process.env.JEST_WORKER_ID)) return true;
  const scriptPath = process.argv[1] || '';
  if (/[\\/]tests?[\\/]|\.(int\.)?spec\.ts$|\.test\.ts$/.test(scriptPath)) return true;
  return false;
}

if (isTestRun()) {
  dotenv.config({ path: '.env.test', override: true });
} else {
  dotenv.config({ path: '.env' });
}

const databaseUrl = process.env.DATABASE_URL;
const databaseHost = process.env.DATABASE_HOST || process.env.PLANETSCALE_DB_HOST || 'localhost';
const databasePort = parseInt(process.env.DATABASE_PORT || '3306', 10);
const databaseUsername = process.env.DATABASE_USER || process.env.PLANETSCALE_DB_USERNAME || 'root';
const databasePassword = process.env.DATABASE_PASSWORD || process.env.PLANETSCALE_DB_PASSWORD || '';
const databaseName = process.env.DATABASE_NAME || process.env.PLANETSCALE_DB || 'partner_db';
const databaseSsl =
  process.env.DATABASE_SSL === 'true' ||
    Boolean(process.env.DATABASE_URL || process.env.PLANETSCALE_DB_HOST)
    ? { rejectUnauthorized: true }
    : undefined;

export const AppDataSource = new DataSource({
  type: 'mysql',
  ...(databaseUrl
    ? { url: databaseUrl }
    : {
      host: databaseHost,
      port: databasePort,
      username: databaseUsername,
      password: databasePassword,
      database: databaseName,
    }),
  ssl: databaseSsl,
  synchronize: true,
  logging: false,
  entities: [
    User,
    UserIdentity,
    Organization,
    OrganizationMembership,
    OrganizationSecurityPolicy,
    MfaRateLimit,
    AuthSession,
    Notification,
    NotificationPreference,
    Program,
    Affiliate,
    AffiliatePortalProfile,
    AffiliateTaxCertificate,
    AffiliatePayoutMethod,
    AffiliateSupportTicket,
    AffiliateInvitation,
    ProgramAffiliate,
    AffiliateApplication,
    TrackingLink,
    Click,
    Attribution,
    ApiKey,
    IdempotencyKey,
    Conversion,
    CommissionRule,
    Commission,
    LedgerAccount,
    LedgerTransaction,
    LedgerEntry,
    FraudReview,
    FraudSettings,
    FraudAssessment,
    FraudSignal,
    AffiliateTrustHistory,
    FraudMetricRollup,
    FraudRule,
    FraudRuleVersion,
    FraudAlert,
    FraudInvestigation,
    FraudHold,
    FraudException,
    PayoutBatch,
    PayoutItem,
    WebhookEndpoint,
    WebhookDelivery,
    AuditLog,
    DemoBooking,
    GoogleCalendarConnection,
    PublicKey,
    UserDevice,
    UserMfaConfig,
    UserRecoveryCode,
    MfaChallenge,
    AuthSecurityEvent,
    Integration,
    OrganizationIntegration,
    IntegrationCredential,
    IntegrationEvent,
    IntegrationOAuthState,
    IntegrationPlatformConfig,
    CrmPipelineMapping,
    CrmFieldMapping,
    CrmEntityMapping,
    IntegrationSyncLog,
    PartnerDeal,
    OrganizationTrial,
    BillingAccount,
    UserLegalAcceptance,
    BillingPlan,
    BillingPlanProviderMapping,
    BillingPlanFeature,
    BillingPlanLimit,
    BillingAddon,
    BillingAddonPurchase,
    BillingPromotion,
    BillingCoupon,
    BillingCouponPlan,
    BillingCouponOrganization,
    BillingCouponRedemption,
    BillingSubscriptionDiscount,
    OrganizationCoupon,
    OrganizationCouponAssignment,
    OrganizationCouponSettings,
    BillingSubscription,
    BillingPayment,
    BillingPaymentEvent,
    BillingRefund,
    BillingInvoice,
    Asset,
    AssetVersion,
    AssetBundle,
    AssetBundleItem,
    AssetTag,
    AffiliateAssetActivity,
    AffiliateAssetFavorite,
    PartnerTier,
    AffiliateTier,
    AffiliateTierHistory,
    Milestone,
    AffiliateMilestoneAchievement,
    AffiliatePerformanceSummary,
    AutomationWorkflow,
    AutomationWorkflowVersion,
    AutomationExecution,
    AutomationScheduledStep,
    AutomationEmailTemplate,
    EmailDesignTemplate,
    EmailDesignSettings,
    OrganizationBranding,
    DocumentDesignTemplate,
    DocumentTemplateVersion,
    GeneratedDocument,
    AutomationEmailLog,
    EmailTemplateVersion,
    EmailTemplateOverride,
    EmailDeliveryLog,
    EmailSuppression,
    RoleDefinition,
    PermissionDefinition,
    RolePermission,
    OrganizationPolicy,
    OrganizationInvitation,
    PlatformSetting,
    BlogPost,
    SecurityEvent,
    SecuritySignal,
    SecurityAlert,
    SecurityInvestigation,
    SecurityIncident,
    SecurityRule,
    SecurityRuleVersion,
    SecurityAction,
    SecurityException,
    ApiRequest,
    ApiExternalCall,
    ApiErrorGroup,
    ApiRateLimitQuota,
    ApiActivityAudit,
    ApiActivityException,
    WebhookEndpointRecord,
    WebhookEventRecord,
    WebhookDeliveryRecord,
    WebhookDeliveryAttemptRecord,
    WebhookEventTypeDefinition,
    WebhookDeadLetterRecord,
    WebhookSecurityIncidentRecord,
    WebhookExceptionRecord,
    WebhookAuditRecord,
    SystemMonitoredService,
    SystemHealthCheckResult,
    SystemIncident,
    SystemServiceDependency,
    SystemDeploymentRecord,
    SystemMaintenanceWindow,
    FeatureFlag,
    FeatureFlagEnvironment,
    FeatureFlagRule,
    FeatureFlagOverride,
    FeatureFlagVersion,
    FeatureFlagDependency,
    FeatureFlagEvaluationMetric,
    FeatureFlagSettingsRecord,
    OrganizationSettings,
    GovernancePolicy,
    GovernancePolicyVersion,
    GovernanceApprovalPolicy,
    GovernanceApprovalRequest,
    GovernanceException,
    GovernanceEmergencyControl,
    GovernanceViolation,
  ],
  migrations: ['src/database/migrations/*.ts'],
  migrationsRun: false,
});


export async function initializeDataSource() {
  if (process.env.UNIT_TEST === 'true' || process.env.TEST_MEMORY_ONLY === 'true') {
    throw new Error('Unit tests must not access the database');
  }

  if (isTestRun()) {
    const targetDb = String((AppDataSource.options as any).database || process.env.DATABASE_NAME || '');
    const targetHost = String((AppDataSource.options as any).host || process.env.DATABASE_HOST || 'localhost');

    const isHostLocal = targetHost === 'localhost' || targetHost === '127.0.0.1';
    const isDbTest = targetDb.endsWith('_test');

    if (!isDbTest || !isHostLocal) {
      throw new Error(
        `FATAL SAFETY GUARD: Test run attempted against non-test database or non-local host! DATABASE_NAME="${targetDb}", DATABASE_HOST="${targetHost}". Tests may only run against databases ending with "_test" on localhost/127.0.0.1.`
      );
    }
  }

  if (!AppDataSource.isInitialized) {
    await AppDataSource.initialize();
  }

  return AppDataSource;
}
