import 'reflect-metadata';
import dotenv from 'dotenv';
import { DataSource } from 'typeorm';
import {
  AuthSession,
  Notification,
  NotificationPreference,
  Organization,
  OrganizationMembership,
  OrganizationSecurityPolicy,
  MfaRateLimit,
  Program,
  User,
  UserIdentity,
  Affiliate,
  AffiliateInvitation,
  ProgramAffiliate,
  AffiliateApplication,
  TrackingLink,
  Click,
  Attribution,
  ApiKey,
  IdempotencyKey,
  Conversion,
  CommissionRule,
  Commission,
  LedgerAccount,
  LedgerTransaction,
  LedgerEntry,
  FraudReview,
  FraudSettings,
  FraudAssessment,
  FraudSignal,
  AffiliateTrustHistory,
  FraudMetricRollup,
  PayoutBatch,
  PayoutItem,
  WebhookEndpoint,
  WebhookDelivery,
  AuditLog,
  DemoBooking,
  PublicKey,
  UserDevice,
  UserMfaConfig,
  UserRecoveryCode,
  MfaChallenge,
  AuthSecurityEvent,
  Integration,
  OrganizationIntegration,
  IntegrationCredential,
  IntegrationEvent,
  IntegrationOAuthState,
  IntegrationPlatformConfig,
  CrmPipelineMapping,
  CrmFieldMapping,
  CrmEntityMapping,
  IntegrationSyncLog,
  PartnerDeal,
  OrganizationTrial,
  BillingPlan,
  BillingPlanProviderMapping,
  BillingPlanFeature,
  BillingPromotion,
  BillingCoupon,
  BillingCouponPlan,
  BillingCouponOrganization,
  BillingCouponRedemption,
  BillingSubscriptionDiscount,
  BillingSubscription,
  BillingPayment,
  BillingPaymentEvent,
  BillingRefund,
  BillingInvoice,
  Asset,
  AssetVersion,
  AssetBundle,
  AssetBundleItem,
  AssetTag,
  AffiliateAssetActivity,
  AffiliateAssetFavorite,
  PartnerTier,
  AffiliateTier,
  AffiliateTierHistory,
  Milestone,
  AffiliateMilestoneAchievement,
  AffiliatePerformanceSummary,
  AutomationWorkflow,
  AutomationWorkflowVersion,
  AutomationExecution,
  AutomationScheduledStep,
  AutomationEmailTemplate,
  EmailDesignTemplate,
  EmailDesignSettings,
  AutomationEmailLog,
  EmailTemplateVersion,
  EmailTemplateOverride,
  EmailDeliveryLog,
  EmailSuppression,
  PlatformSetting,
} from './schema';
import {
  RoleDefinition,
  PermissionDefinition,
  RolePermission,
  OrganizationPolicy,
  OrganizationInvitation,
} from './schema-rbac';

dotenv.config();

const databaseUrl = process.env.DATABASE_URL;
const databaseHost = process.env.DATABASE_HOST || process.env.PLANETSCALE_DB_HOST || 'localhost';
const databasePort = parseInt(process.env.DATABASE_PORT || '3306', 10);
const databaseUsername = process.env.DATABASE_USER || process.env.PLANETSCALE_DB_USERNAME || 'root';
const databasePassword = process.env.DATABASE_PASSWORD || process.env.PLANETSCALE_DB_PASSWORD || '';
const databaseName = process.env.DATABASE_NAME || process.env.PLANETSCALE_DB || 'partner_db';
const databaseSsl =
  process.env.DATABASE_SSL === 'true' ||
  Boolean(process.env.DATABASE_URL || process.env.PLANETSCALE_DB_HOST)
    ? { rejectUnauthorized: true }
    : undefined;

export const AppDataSource = new DataSource({
  type: 'mysql',
  ...(databaseUrl
    ? { url: databaseUrl }
    : {
        host: databaseHost,
        port: databasePort,
        username: databaseUsername,
        password: databasePassword,
        database: databaseName,
      }),
  ssl: databaseSsl,
  synchronize: true,
  logging: false,
  entities: [
    User,
    UserIdentity,
    Organization,
    OrganizationMembership,
    OrganizationSecurityPolicy,
    MfaRateLimit,
    AuthSession,
    Notification,
    NotificationPreference,
    Program,
    Affiliate,
    AffiliateInvitation,
    ProgramAffiliate,
    AffiliateApplication,
    TrackingLink,
    Click,
    Attribution,
    ApiKey,
    IdempotencyKey,
    Conversion,
    CommissionRule,
    Commission,
    LedgerAccount,
    LedgerTransaction,
    LedgerEntry,
    FraudReview,
    FraudSettings,
    FraudAssessment,
    FraudSignal,
    AffiliateTrustHistory,
    FraudMetricRollup,
    PayoutBatch,
    PayoutItem,
    WebhookEndpoint,
    WebhookDelivery,
    AuditLog,
    DemoBooking,
    PublicKey,
    UserDevice,
    UserMfaConfig,
    UserRecoveryCode,
    MfaChallenge,
    AuthSecurityEvent,
    Integration,
    OrganizationIntegration,
    IntegrationCredential,
    IntegrationEvent,
    IntegrationOAuthState,
    IntegrationPlatformConfig,
    CrmPipelineMapping,
    CrmFieldMapping,
    CrmEntityMapping,
    IntegrationSyncLog,
    PartnerDeal,
    OrganizationTrial,
    BillingPlan,
    BillingPlanProviderMapping,
    BillingPlanFeature,
    BillingPromotion,
    BillingCoupon,
    BillingCouponPlan,
    BillingCouponOrganization,
    BillingCouponRedemption,
    BillingSubscriptionDiscount,
    BillingSubscription,
    BillingPayment,
    BillingPaymentEvent,
    BillingRefund,
    BillingInvoice,
    Asset,
    AssetVersion,
    AssetBundle,
    AssetBundleItem,
    AssetTag,
    AffiliateAssetActivity,
    AffiliateAssetFavorite,
    PartnerTier,
    AffiliateTier,
    AffiliateTierHistory,
    Milestone,
    AffiliateMilestoneAchievement,
    AffiliatePerformanceSummary,
    AutomationWorkflow,
    AutomationWorkflowVersion,
    AutomationExecution,
    AutomationScheduledStep,
    AutomationEmailTemplate,
    EmailDesignTemplate,
    EmailDesignSettings,
    AutomationEmailLog,
    EmailTemplateVersion,
    EmailTemplateOverride,
    EmailDeliveryLog,
    EmailSuppression,
    RoleDefinition,
    PermissionDefinition,
    RolePermission,
    OrganizationPolicy,
    OrganizationInvitation,
    PlatformSetting,
  ],
  migrations: ['src/database/migrations/*.ts'],
  migrationsRun: false,
});

export async function initializeDataSource() {
  if (!AppDataSource.isInitialized) {
    await AppDataSource.initialize();
  }

  return AppDataSource;
}
