import 'reflect-metadata';
import dotenv from 'dotenv';
import { DataSource } from 'typeorm';
import {
  AuthSession,
  Organization,
  OrganizationMembership,
  Program,
  User,
  Affiliate,
  ProgramAffiliate,
  AffiliateApplication,
  TrackingLink,
  Click,
  Attribution,
  ApiKey,
  IdempotencyKey,
  Conversion,
  CommissionRule,
  Commission,
  LedgerAccount,
  LedgerTransaction,
  LedgerEntry,
  FraudReview,
  FraudSettings,
  FraudAssessment,
  FraudSignal,
  AffiliateTrustHistory,
  FraudMetricRollup,
  PayoutBatch,
  PayoutItem,
  WebhookEndpoint,
  WebhookDelivery,
  AuditLog,
  PublicKey,
  Integration,
  OrganizationIntegration,
  IntegrationCredential,
  IntegrationEvent,
  IntegrationOAuthState,
} from './schema';
import {
  RoleDefinition,
  PermissionDefinition,
  RolePermission,
  OrganizationPolicy,
  OrganizationInvitation,
} from './schema-rbac';

dotenv.config();

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DATABASE_HOST || 'localhost',
  port: parseInt(process.env.DATABASE_PORT || '3306', 10),
  username: process.env.DATABASE_USER || 'root',
  password: process.env.DATABASE_PASSWORD || '',
  database: process.env.DATABASE_NAME || 'partner_db',
  synchronize: true,
  logging: false,
  entities: [
    User,
    Organization,
    OrganizationMembership,
    AuthSession,
    Program,
    Affiliate,
    ProgramAffiliate,
    AffiliateApplication,
    TrackingLink,
    Click,
    Attribution,
    ApiKey,
    IdempotencyKey,
    Conversion,
    CommissionRule,
    Commission,
    LedgerAccount,
    LedgerTransaction,
    LedgerEntry,
    FraudReview,
    FraudSettings,
    FraudAssessment,
    FraudSignal,
    AffiliateTrustHistory,
    FraudMetricRollup,
    PayoutBatch,
    PayoutItem,
    WebhookEndpoint,
    WebhookDelivery,
    AuditLog,
    PublicKey,
    Integration,
    OrganizationIntegration,
    IntegrationCredential,
    IntegrationEvent,
    IntegrationOAuthState,
    RoleDefinition,
    PermissionDefinition,
    RolePermission,
    OrganizationPolicy,
    OrganizationInvitation,
  ],
  migrations: ['src/database/migrations/*.ts'],
  migrationsRun: false,
});

export async function initializeDataSource() {
  if (!AppDataSource.isInitialized) {
    await AppDataSource.initialize();
  }

  return AppDataSource;
}
