export const PERMISSIONS = [
  { code: 'organization.read', resource: 'organization', action: 'read', description: 'View organization details' },
  { code: 'organization.update', resource: 'organization', action: 'update', description: 'Edit organization settings' },

  { code: 'members.read', resource: 'members', action: 'read', description: 'View team members' },
  { code: 'members.invite', resource: 'members', action: 'invite', description: 'Invite new members' },
  { code: 'members.update', resource: 'members', action: 'update', description: 'Change member roles or program access' },
  { code: 'members.remove', resource: 'members', action: 'remove', description: 'Remove team members' },

  { code: 'roles.read', resource: 'roles', action: 'read', description: 'View roles and permissions' },
  { code: 'roles.create', resource: 'roles', action: 'create', description: 'Create custom roles' },
  { code: 'roles.update', resource: 'roles', action: 'update', description: 'Update custom roles' },
  { code: 'roles.delete', resource: 'roles', action: 'delete', description: 'Delete custom roles' },
  { code: 'roles.assign', resource: 'roles', action: 'assign', description: 'Assign roles to members' },

  { code: 'programs.read', resource: 'programs', action: 'read', description: 'View programs' },
  { code: 'programs.create', resource: 'programs', action: 'create', description: 'Create programs' },
  { code: 'programs.update', resource: 'programs', action: 'update', description: 'Edit programs' },
  { code: 'programs.archive', resource: 'programs', action: 'archive', description: 'Archive programs' },

  { code: 'affiliates.read', resource: 'affiliates', action: 'read', description: 'View affiliates' },
  { code: 'affiliates.create', resource: 'affiliates', action: 'create', description: 'Create affiliates' },
  { code: 'affiliates.update', resource: 'affiliates', action: 'update', description: 'Edit affiliates' },
  { code: 'affiliates.approve', resource: 'affiliates', action: 'approve', description: 'Approve affiliates' },
  { code: 'affiliates.suspend', resource: 'affiliates', action: 'suspend', description: 'Suspend affiliates' },

  { code: 'links.read', resource: 'links', action: 'read', description: 'View tracking links' },
  { code: 'links.create', resource: 'links', action: 'create', description: 'Create tracking links' },
  { code: 'links.update', resource: 'links', action: 'update', description: 'Edit tracking links' },

  { code: 'conversions.read', resource: 'conversions', action: 'read', description: 'View conversions' },
  { code: 'conversions.update', resource: 'conversions', action: 'update', description: 'Edit conversions' },

  { code: 'commissions.read', resource: 'commissions', action: 'read', description: 'View commissions' },
  { code: 'commissions.create', resource: 'commissions', action: 'create', description: 'Create commission rules' },
  { code: 'commissions.approve', resource: 'commissions', action: 'approve', description: 'Approve commissions' },
  { code: 'commissions.reverse', resource: 'commissions', action: 'reverse', description: 'Reverse commissions' },

  { code: 'fraud.read', resource: 'fraud', action: 'read', description: 'View fraud reviews' },
  { code: 'fraud.review', resource: 'fraud', action: 'review', description: 'Review fraud cases' },
  { code: 'fraud.settings.update', resource: 'fraud', action: 'settings.update', description: 'Update fraud engine settings' },
  { code: 'affiliates.suspend_for_fraud', resource: 'affiliates', action: 'suspend_for_fraud', description: 'Suspend affiliate due to fraud review' },

  { code: 'payouts.read', resource: 'payouts', action: 'read', description: 'View payouts' },
  { code: 'payouts.create', resource: 'payouts', action: 'create', description: 'Create payouts' },
  { code: 'payouts.approve', resource: 'payouts', action: 'approve', description: 'Approve payouts' },

  { code: 'analytics.read', resource: 'analytics', action: 'read', description: 'View analytics' },

  { code: 'integrations.read', resource: 'integrations', action: 'read', description: 'View integrations' },
  { code: 'integrations.manage', resource: 'integrations', action: 'manage', description: 'Manage integrations' },
  { code: 'integrations.create', resource: 'integrations', action: 'create', description: 'Create platform integrations' },
  { code: 'integrations.update', resource: 'integrations', action: 'update', description: 'Update platform integrations' },
  { code: 'integrations.disable', resource: 'integrations', action: 'disable', description: 'Disable platform integrations' },
  { code: 'integrations.health.read', resource: 'integrations', action: 'health.read', description: 'View integration health' },
  { code: 'integrations.connections.read', resource: 'integrations', action: 'connections.read', description: 'View organization integration connections' },
  { code: 'integrations.events.read', resource: 'integrations', action: 'events.read', description: 'View integration event pipeline activity' },
  { code: 'integrations.secrets.update', resource: 'integrations', action: 'secrets.update', description: 'Update encrypted integration secrets' },

  { code: 'api_keys.read', resource: 'api_keys', action: 'read', description: 'View API keys' },
  { code: 'api_keys.create', resource: 'api_keys', action: 'create', description: 'Create API keys' },
  { code: 'api_keys.revoke', resource: 'api_keys', action: 'revoke', description: 'Revoke API keys' },

  { code: 'webhooks.read', resource: 'webhooks', action: 'read', description: 'View webhooks' },
  { code: 'webhooks.create', resource: 'webhooks', action: 'create', description: 'Create webhooks' },
  { code: 'webhooks.update', resource: 'webhooks', action: 'update', description: 'Update webhooks' },
  { code: 'webhooks.delete', resource: 'webhooks', action: 'delete', description: 'Delete webhooks' },

  { code: 'audit.read', resource: 'audit', action: 'read', description: 'View audit logs' },

  { code: 'billing.view', resource: 'billing', action: 'view', description: 'View plans, subscription, invoices, and payments' },
  { code: 'billing.manage', resource: 'billing', action: 'manage', description: 'Manage subscription, upgrades, downgrades, and billing profile' },
  { code: 'billing.subscribe', resource: 'billing', action: 'subscribe', description: 'Start or change organization subscriptions' },
  { code: 'billing.cancel', resource: 'billing', action: 'cancel', description: 'Cancel organization subscriptions' },
  { code: 'billing.refund', resource: 'billing', action: 'refund', description: 'Issue payment refunds' },
  { code: 'billing.admin', resource: 'billing', action: 'admin', description: 'Administer billing across all organizations' },

  { code: 'organization_policies.read', resource: 'organization_policies', action: 'read', description: 'View access policies' },
  { code: 'organization_policies.create', resource: 'organization_policies', action: 'create', description: 'Create access policies' },
  { code: 'organization_policies.update', resource: 'organization_policies', action: 'update', description: 'Update access policies' },
  { code: 'organization_policies.delete', resource: 'organization_policies', action: 'delete', description: 'Delete access policies' },
];

export const BUILT_IN_ROLES = {
  SUPER_ADMIN: {
    name: 'Super Admin',
    code: 'SUPER_ADMIN',
    description: 'Platform administrator with access across all tenant organizations',
    permissions: ['*'],
  },
  OWNER: {
    name: 'Owner',
    code: 'OWNER',
    description: 'Full organization ownership access',
    permissions: ['*'],
  },
  ADMIN: {
    name: 'Admin',
    code: 'ADMIN',
    description: 'Organization administrator with broad operational access',
    permissions: [
      'organization.read',
      'organization.update',
      'members.read',
      'members.invite',
      'members.update',
      'members.remove',
      'roles.read',
      'roles.assign',
      'programs.create',
      'programs.read',
      'programs.update',
      'programs.archive',
      'affiliates.read',
      'affiliates.create',
      'affiliates.update',
      'affiliates.approve',
      'affiliates.suspend',
      'affiliates.suspend_for_fraud',
      'links.read',
      'links.create',
      'links.update',
      'conversions.read',
      'conversions.update',
      'commissions.read',
      'commissions.create',
      'commissions.approve',
      'commissions.reverse',
      'payouts.read',
      'payouts.create',
      'payouts.approve',
      'analytics.read',
      'fraud.read',
      'fraud.review',
      'fraud.settings.update',
      'integrations.read',
      'integrations.manage',
      'api_keys.read',
      'api_keys.create',
      'api_keys.revoke',
      'webhooks.read',
      'webhooks.create',
      'webhooks.update',
      'webhooks.delete',
      'audit.read',
      'billing.view',
      'billing.manage',
      'billing.subscribe',
      'billing.cancel',
    ],
  },
  PROGRAM_MANAGER: {
    name: 'Program Manager',
    code: 'PROGRAM_MANAGER',
    description: 'Manage programs, affiliates, and links',
    permissions: [
      'programs.read',
      'programs.create',
      'programs.update',
      'affiliates.read',
      'affiliates.create',
      'affiliates.update',
      'affiliates.approve',
      'links.read',
      'links.create',
      'links.update',
      'conversions.read',
      'commissions.read',
      'analytics.read',
    ],
  },
  AFFILIATE_MANAGER: {
    name: 'Affiliate Manager',
    code: 'AFFILIATE_MANAGER',
    description: 'Manage affiliates and tracking links',
    permissions: [
      'affiliates.read',
      'affiliates.create',
      'affiliates.update',
      'affiliates.approve',
      'affiliates.suspend',
      'links.read',
      'links.create',
      'conversions.read',
      'commissions.read',
      'analytics.read',
    ],
  },
  FINANCE: {
    name: 'Finance',
    code: 'FINANCE',
    description: 'Manage payout and commission approvals',
    permissions: [
      'commissions.read',
      'commissions.approve',
      'commissions.reverse',
      'payouts.read',
      'payouts.create',
      'payouts.approve',
      'billing.view',
      'conversions.read',
      'analytics.read',
    ],
  },
  RISK_ANALYST: {
    name: 'Risk Analyst',
    code: 'RISK_ANALYST',
    description: 'Review fraud and risk metrics',
    permissions: [
      'fraud.read',
      'fraud.review',
      'conversions.read',
      'affiliates.read',
      'analytics.read',
    ],
  },
  ANALYST: {
    name: 'Analyst',
    code: 'ANALYST',
    description: 'View program and revenue analytics',
    permissions: [
      'programs.read',
      'affiliates.read',
      'conversions.read',
      'commissions.read',
      'fraud.read',
      'payouts.read',
      'analytics.read',
    ],
  },
  DEVELOPER: {
    name: 'Developer',
    code: 'DEVELOPER',
    description: 'Manage integrations, API keys and webhooks',
    permissions: [
      'programs.read',
      'integrations.read',
      'integrations.manage',
      'api_keys.read',
      'api_keys.create',
      'api_keys.revoke',
      'webhooks.read',
      'webhooks.create',
      'webhooks.update',
      'webhooks.delete',
    ],
  },
  VIEWER: {
    name: 'Viewer',
    code: 'VIEWER',
    description: 'Read-only access across reports and resources',
    permissions: [
      'programs.read',
      'affiliates.read',
      'conversions.read',
      'commissions.read',
      'fraud.read',
      'payouts.read',
      'analytics.read',
    ],
  },
};

export const BUILT_IN_ROLE_CODES = Object.keys(BUILT_IN_ROLES) as Array<keyof typeof BUILT_IN_ROLES>;

export const PERMISSION_ALIASES: Record<string, string[]> = {
  'manage.organization': [
    'organization.update',
    'organization.read',
    'members.invite',
    'members.update',
    'members.remove',
    'roles.read',
    'roles.assign',
  ],
  'view.organization': ['organization.read'],
  'manage.programs': ['programs.read', 'programs.create', 'programs.update', 'programs.archive'],
  'manage.affiliates': ['affiliates.read', 'affiliates.create', 'affiliates.update', 'affiliates.approve', 'affiliates.suspend'],
  'manage.commissions': ['commissions.read', 'commissions.create', 'commissions.approve', 'commissions.reverse'],
  'manage.payouts': ['payouts.read', 'payouts.create', 'payouts.approve'],
  'manage.api_keys': ['api_keys.read', 'api_keys.create', 'api_keys.revoke'],
  'manage.webhooks': ['webhooks.read', 'webhooks.create', 'webhooks.update', 'webhooks.delete'],
  'view.billing': ['billing.view'],
  'manage.billing': ['billing.view', 'billing.manage', 'billing.subscribe', 'billing.cancel'],
  'view.integrations': ['integrations.read'],
  'view.programs': ['programs.read'],
  'view.affiliates': ['affiliates.read'],
  'view.conversions': ['conversions.read'],
  'view.fraud': ['fraud.read'],
  'manage.links': ['links.read', 'links.create', 'links.update'],
};
