export const PERMISSIONS = [
  { code: 'organization.read', resource: 'organization', action: 'read', description: 'View organization details' },
  { code: 'organization.update', resource: 'organization', action: 'update', description: 'Edit organization settings' },

  { code: 'members.read', resource: 'members', action: 'read', description: 'View team members' },
  { code: 'members.invite', resource: 'members', action: 'invite', description: 'Invite new members' },
  { code: 'members.update', resource: 'members', action: 'update', description: 'Change member roles or program access' },
  { code: 'members.remove', resource: 'members', action: 'remove', description: 'Remove team members' },

  { code: 'roles.read', resource: 'roles', action: 'read', description: 'View roles and permissions' },
  { code: 'roles.create', resource: 'roles', action: 'create', description: 'Create custom roles' },
  { code: 'roles.update', resource: 'roles', action: 'update', description: 'Update custom roles' },
  { code: 'roles.delete', resource: 'roles', action: 'delete', description: 'Delete custom roles' },
  { code: 'roles.assign', resource: 'roles', action: 'assign', description: 'Assign roles to members' },

  { code: 'programs.read', resource: 'programs', action: 'read', description: 'View programs' },
  { code: 'programs.create', resource: 'programs', action: 'create', description: 'Create programs' },
  { code: 'programs.update', resource: 'programs', action: 'update', description: 'Edit programs' },
  { code: 'programs.archive', resource: 'programs', action: 'archive', description: 'Archive programs' },

  { code: 'affiliates.read', resource: 'affiliates', action: 'read', description: 'View affiliates' },
  { code: 'affiliates.create', resource: 'affiliates', action: 'create', description: 'Create affiliates' },
  { code: 'affiliates.update', resource: 'affiliates', action: 'update', description: 'Edit affiliates' },
  { code: 'affiliates.approve', resource: 'affiliates', action: 'approve', description: 'Approve affiliates' },
  { code: 'affiliates.suspend', resource: 'affiliates', action: 'suspend', description: 'Suspend affiliates' },

  { code: 'links.read', resource: 'links', action: 'read', description: 'View tracking links' },
  { code: 'links.create', resource: 'links', action: 'create', description: 'Create tracking links' },
  { code: 'links.update', resource: 'links', action: 'update', description: 'Edit tracking links' },

  { code: 'conversions.read', resource: 'conversions', action: 'read', description: 'View conversions' },
  { code: 'conversions.update', resource: 'conversions', action: 'update', description: 'Edit conversions' },

  { code: 'commissions.read', resource: 'commissions', action: 'read', description: 'View commissions' },
  { code: 'commissions.create', resource: 'commissions', action: 'create', description: 'Create commission rules' },
  { code: 'commissions.approve', resource: 'commissions', action: 'approve', description: 'Approve commissions' },
  { code: 'commissions.reverse', resource: 'commissions', action: 'reverse', description: 'Reverse commissions' },

  { code: 'fraud.read', resource: 'fraud', action: 'read', description: 'View fraud reviews' },
  { code: 'fraud.review', resource: 'fraud', action: 'review', description: 'Review fraud cases' },
  { code: 'fraud.settings.update', resource: 'fraud', action: 'settings.update', description: 'Update fraud engine settings' },
  { code: 'affiliates.suspend_for_fraud', resource: 'affiliates', action: 'suspend_for_fraud', description: 'Suspend affiliate due to fraud review' },

  { code: 'payouts.read', resource: 'payouts', action: 'read', description: 'View payouts' },
  { code: 'payouts.create', resource: 'payouts', action: 'create', description: 'Create payouts' },
  { code: 'payouts.approve', resource: 'payouts', action: 'approve', description: 'Approve payouts' },

  { code: 'analytics.read', resource: 'analytics', action: 'read', description: 'View analytics' },

  { code: 'assets.view', resource: 'assets', action: 'view', description: 'View marketing assets' },
  { code: 'assets.create', resource: 'assets', action: 'create', description: 'Create marketing assets' },
  { code: 'assets.edit', resource: 'assets', action: 'edit', description: 'Edit marketing assets and versions' },
  { code: 'assets.delete', resource: 'assets', action: 'delete', description: 'Archive or delete marketing assets' },
  { code: 'assets.publish', resource: 'assets', action: 'publish', description: 'Publish assets to affiliates' },
  { code: 'assets.download', resource: 'assets', action: 'download', description: 'Download authorized marketing assets' },
  { code: 'assetBundles.view', resource: 'assetBundles', action: 'view', description: 'View marketing asset bundles' },
  { code: 'assetBundles.create', resource: 'assetBundles', action: 'create', description: 'Create marketing asset bundles' },
  { code: 'assetBundles.edit', resource: 'assetBundles', action: 'edit', description: 'Edit marketing asset bundles' },
  { code: 'assetBundles.delete', resource: 'assetBundles', action: 'delete', description: 'Archive or delete marketing asset bundles' },
  { code: 'assetBundles.publish', resource: 'assetBundles', action: 'publish', description: 'Publish marketing asset bundles' },

  { code: 'integrations.read', resource: 'integrations', action: 'read', description: 'View integrations' },
  { code: 'integrations.manage', resource: 'integrations', action: 'manage', description: 'Manage integrations' },
  { code: 'integrations.view', resource: 'integrations', action: 'view', description: 'View CRM integration connections' },
  { code: 'integrations.configure', resource: 'integrations', action: 'configure', description: 'Configure CRM integration settings' },
  { code: 'integrations.connect', resource: 'integrations', action: 'connect', description: 'Connect CRM integrations' },
  { code: 'integrations.disconnect', resource: 'integrations', action: 'disconnect', description: 'Disconnect CRM integrations' },
  { code: 'integrations.test', resource: 'integrations', action: 'test', description: 'Test CRM integration health' },
  { code: 'integrations.sync', resource: 'integrations', action: 'sync', description: 'Run CRM synchronization' },
  { code: 'integrations.create', resource: 'integrations', action: 'create', description: 'Create platform integrations' },
  { code: 'integrations.update', resource: 'integrations', action: 'update', description: 'Update platform integrations' },
  { code: 'integrations.disable', resource: 'integrations', action: 'disable', description: 'Disable platform integrations' },
  { code: 'integrations.health.read', resource: 'integrations', action: 'health.read', description: 'View integration health' },
  { code: 'integrations.connections.read', resource: 'integrations', action: 'connections.read', description: 'View organization integration connections' },
  { code: 'integrations.events.read', resource: 'integrations', action: 'events.read', description: 'View integration event pipeline activity' },
  { code: 'integrations.secrets.update', resource: 'integrations', action: 'secrets.update', description: 'Update encrypted integration secrets' },

  { code: 'deals.view', resource: 'deals', action: 'view', description: 'View partner B2B deals' },
  { code: 'deals.create', resource: 'deals', action: 'create', description: 'Register partner B2B deals' },
  { code: 'deals.approve', resource: 'deals', action: 'approve', description: 'Approve partner B2B deals' },
  { code: 'deals.reject', resource: 'deals', action: 'reject', description: 'Reject partner B2B deals' },
  { code: 'deals.edit', resource: 'deals', action: 'edit', description: 'Edit partner B2B deals' },
  { code: 'deals.sync', resource: 'deals', action: 'sync', description: 'Sync partner deals to CRM' },
  { code: 'deals.viewFinancials', resource: 'deals', action: 'viewFinancials', description: 'View deal financials and commission outcomes' },

  { code: 'api_keys.read', resource: 'api_keys', action: 'read', description: 'View API keys' },
  { code: 'api_keys.create', resource: 'api_keys', action: 'create', description: 'Create API keys' },
  { code: 'api_keys.revoke', resource: 'api_keys', action: 'revoke', description: 'Revoke API keys' },

  { code: 'webhooks.read', resource: 'webhooks', action: 'read', description: 'View webhooks' },
  { code: 'webhooks.create', resource: 'webhooks', action: 'create', description: 'Create webhooks' },
  { code: 'webhooks.update', resource: 'webhooks', action: 'update', description: 'Update webhooks' },
  { code: 'webhooks.delete', resource: 'webhooks', action: 'delete', description: 'Delete webhooks' },

  { code: 'audit.read', resource: 'audit', action: 'read', description: 'View audit logs' },

  { code: 'billing.view', resource: 'billing', action: 'view', description: 'View plans, subscription, invoices, and payments' },
  { code: 'billing.manage', resource: 'billing', action: 'manage', description: 'Manage subscription, upgrades, downgrades, and billing profile' },
  { code: 'billing.subscribe', resource: 'billing', action: 'subscribe', description: 'Start or change organization subscriptions' },
  { code: 'billing.cancel', resource: 'billing', action: 'cancel', description: 'Cancel organization subscriptions' },
  { code: 'billing.refund', resource: 'billing', action: 'refund', description: 'Issue payment refunds' },
  { code: 'billing.admin', resource: 'billing', action: 'admin', description: 'Administer billing across all organizations' },
  { code: 'billing.coupons.read', resource: 'billing.coupons', action: 'read', description: 'View PartnerIQ billing coupons' },
  { code: 'billing.coupons.create', resource: 'billing.coupons', action: 'create', description: 'Create PartnerIQ billing coupons' },
  { code: 'billing.coupons.update', resource: 'billing.coupons', action: 'update', description: 'Update PartnerIQ billing coupons' },
  { code: 'billing.coupons.activate', resource: 'billing.coupons', action: 'activate', description: 'Activate PartnerIQ billing coupons' },
  { code: 'billing.coupons.archive', resource: 'billing.coupons', action: 'archive', description: 'Archive PartnerIQ billing coupons' },
  { code: 'billing.coupons.redemptions.read', resource: 'billing.coupons', action: 'redemptions.read', description: 'View billing coupon redemptions' },
  { code: 'billing.coupons.analytics.read', resource: 'billing.coupons', action: 'analytics.read', description: 'View billing coupon analytics' },

  { code: 'organization_policies.read', resource: 'organization_policies', action: 'read', description: 'View access policies' },
  { code: 'organization_policies.create', resource: 'organization_policies', action: 'create', description: 'Create access policies' },
  { code: 'organization_policies.update', resource: 'organization_policies', action: 'update', description: 'Update access policies' },
  { code: 'organization_policies.delete', resource: 'organization_policies', action: 'delete', description: 'Delete access policies' },

  { code: 'tiers.view', resource: 'tiers', action: 'view', description: 'View partner tiers' },
  { code: 'tiers.create', resource: 'tiers', action: 'create', description: 'Create partner tiers' },
  { code: 'tiers.edit', resource: 'tiers', action: 'edit', description: 'Edit partner tiers' },
  { code: 'tiers.delete', resource: 'tiers', action: 'delete', description: 'Delete partner tiers' },
  { code: 'tiers.assign', resource: 'tiers', action: 'assign', description: 'Manually assign and lock affiliate tiers' },

  { code: 'milestones.view', resource: 'milestones', action: 'view', description: 'View milestones and rewards' },
  { code: 'milestones.create', resource: 'milestones', action: 'create', description: 'Create milestone rules' },
  { code: 'milestones.edit', resource: 'milestones', action: 'edit', description: 'Edit milestone rules' },
  { code: 'milestones.delete', resource: 'milestones', action: 'delete', description: 'Delete milestone rules' },

  { code: 'automations.view', resource: 'automations', action: 'view', description: 'View onboarding and automation workflows' },
  { code: 'automations.create', resource: 'automations', action: 'create', description: 'Create automation workflows' },
  { code: 'automations.edit', resource: 'automations', action: 'edit', description: 'Edit automation workflows and templates' },
  { code: 'automations.publish', resource: 'automations', action: 'publish', description: 'Publish or pause automation workflows' },
  { code: 'automations.pause', resource: 'automations', action: 'pause', description: 'Pause active automations' },
  { code: 'automations.delete', resource: 'automations', action: 'delete', description: 'Archive or delete automations' },

  { code: 'performance.view', resource: 'performance', action: 'view', description: 'View affiliate performance and leaderboard' },
  { code: 'performance.manage', resource: 'performance', action: 'manage', description: 'Manage performance settings and period resets' },
  { code: 'rewards.grant', resource: 'rewards', action: 'grant', description: 'Manually grant rewards, badges, and bonuses' },
];

export const BUILT_IN_ROLES = {
  SUPER_ADMIN: {
    name: 'Super Admin',
    code: 'SUPER_ADMIN',
    description: 'Platform administrator with access across all tenant organizations',
    permissions: ['*'],
  },
  OWNER: {
    name: 'Owner',
    code: 'OWNER',
    description: 'Full organization ownership access',
    permissions: ['*'],
  },
  ADMIN: {
    name: 'Admin',
    code: 'ADMIN',
    description: 'Organization administrator with broad operational access',
    permissions: [
      'organization.read',
      'organization.update',
      'members.read',
      'members.invite',
      'members.update',
      'members.remove',
      'roles.read',
      'roles.assign',
      'programs.create',
      'programs.read',
      'programs.update',
      'programs.archive',
      'affiliates.read',
      'affiliates.create',
      'affiliates.update',
      'affiliates.approve',
      'affiliates.suspend',
      'affiliates.suspend_for_fraud',
      'links.read',
      'links.create',
      'links.update',
      'conversions.read',
      'conversions.update',
      'commissions.read',
      'commissions.create',
      'commissions.approve',
      'commissions.reverse',
      'payouts.read',
      'payouts.create',
      'payouts.approve',
      'analytics.read',
      'assets.view',
      'assets.create',
      'assets.edit',
      'assets.delete',
      'assets.publish',
      'assets.download',
      'assetBundles.view',
      'assetBundles.create',
      'assetBundles.edit',
      'assetBundles.delete',
      'assetBundles.publish',
      'fraud.read',
      'fraud.review',
      'fraud.settings.update',
      'integrations.read',
      'integrations.manage',
      'integrations.view',
      'integrations.configure',
      'integrations.connect',
      'integrations.disconnect',
      'integrations.test',
      'integrations.sync',
      'deals.view',
      'deals.create',
      'deals.approve',
      'deals.reject',
      'deals.edit',
      'deals.sync',
      'deals.viewFinancials',
      'api_keys.read',
      'api_keys.create',
      'api_keys.revoke',
      'webhooks.read',
      'webhooks.create',
      'webhooks.update',
      'webhooks.delete',
      'audit.read',
      'billing.view',
      'billing.manage',
      'billing.subscribe',
      'billing.cancel',
      'tiers.view',
      'tiers.create',
      'tiers.edit',
      'tiers.delete',
      'tiers.assign',
      'milestones.view',
      'milestones.create',
      'milestones.edit',
      'milestones.delete',
      'automations.view',
      'automations.create',
      'automations.edit',
      'automations.publish',
      'automations.pause',
      'automations.delete',
      'performance.view',
      'performance.manage',
      'rewards.grant',
    ],
  },
  PROGRAM_MANAGER: {
    name: 'Program Manager',
    code: 'PROGRAM_MANAGER',
    description: 'Manage programs, affiliates, and links',
    permissions: [
      'programs.read',
      'programs.create',
      'programs.update',
      'affiliates.read',
      'affiliates.create',
      'affiliates.update',
      'affiliates.approve',
      'links.read',
      'links.create',
      'links.update',
      'conversions.read',
      'commissions.read',
      'analytics.read',
      'deals.view',
      'deals.create',
      'deals.approve',
      'deals.reject',
      'deals.sync',
      'deals.viewFinancials',
      'assets.view',
      'assets.create',
      'assets.edit',
      'assets.publish',
      'assets.download',
      'assetBundles.view',
      'assetBundles.create',
      'assetBundles.edit',
      'assetBundles.publish',
      'tiers.view',
      'tiers.create',
      'tiers.edit',
      'tiers.assign',
      'milestones.view',
      'milestones.create',
      'milestones.edit',
      'automations.view',
      'automations.create',
      'automations.edit',
      'automations.publish',
      'automations.pause',
      'performance.view',
      'performance.manage',
      'rewards.grant',
    ],
  },
  AFFILIATE_MANAGER: {
    name: 'Affiliate Manager',
    code: 'AFFILIATE_MANAGER',
    description: 'Manage affiliates and tracking links',
    permissions: [
      'affiliates.read',
      'affiliates.create',
      'affiliates.update',
      'affiliates.approve',
      'affiliates.suspend',
      'links.read',
      'links.create',
      'conversions.read',
      'commissions.read',
      'analytics.read',
      'deals.view',
      'deals.create',
      'deals.approve',
      'deals.reject',
      'assets.view',
      'assets.create',
      'assets.edit',
      'assets.publish',
      'assets.download',
      'assetBundles.view',
      'assetBundles.create',
      'assetBundles.edit',
      'assetBundles.publish',
      'tiers.view',
      'tiers.assign',
      'milestones.view',
      'automations.view',
      'performance.view',
      'rewards.grant',
    ],
  },
  FINANCE: {
    name: 'Finance',
    code: 'FINANCE',
    description: 'Manage payout and commission approvals',
    permissions: [
      'commissions.read',
      'commissions.approve',
      'commissions.reverse',
      'payouts.read',
      'payouts.create',
      'payouts.approve',
      'billing.view',
      'conversions.read',
      'analytics.read',
      'assets.view',
      'assetBundles.view',
      'tiers.view',
      'milestones.view',
      'performance.view',
    ],
  },
  RISK_ANALYST: {
    name: 'Risk Analyst',
    code: 'RISK_ANALYST',
    description: 'Review fraud and risk metrics',
    permissions: [
      'fraud.read',
      'fraud.review',
      'conversions.read',
      'affiliates.read',
      'analytics.read',
      'assets.view',
      'assetBundles.view',
      'performance.view',
    ],
  },
  ANALYST: {
    name: 'Analyst',
    code: 'ANALYST',
    description: 'View program and revenue analytics',
    permissions: [
      'programs.read',
      'affiliates.read',
      'conversions.read',
      'commissions.read',
      'deals.view',
      'deals.viewFinancials',
      'fraud.read',
      'payouts.read',
      'analytics.read',
      'deals.view',
      'tiers.view',
      'milestones.view',
      'automations.view',
      'performance.view',
    ],
  },
  DEVELOPER: {
    name: 'Developer',
    code: 'DEVELOPER',
    description: 'Manage integrations, API keys and webhooks',
    permissions: [
      'programs.read',
      'integrations.read',
      'integrations.manage',
      'integrations.view',
      'integrations.configure',
      'integrations.connect',
      'integrations.disconnect',
      'integrations.test',
      'integrations.sync',
      'api_keys.read',
      'api_keys.create',
      'api_keys.revoke',
      'webhooks.read',
      'webhooks.create',
      'webhooks.update',
      'webhooks.delete',
      'automations.view',
    ],
  },
  VIEWER: {
    name: 'Viewer',
    code: 'VIEWER',
    description: 'Read-only access across reports and resources',
    permissions: [
      'programs.read',
      'affiliates.read',
      'conversions.read',
      'commissions.read',
      'fraud.read',
      'payouts.read',
      'analytics.read',
      'deals.view',
      'tiers.view',
      'milestones.view',
      'performance.view',
    ],
  },
};

export const BUILT_IN_ROLE_CODES = Object.keys(BUILT_IN_ROLES) as Array<keyof typeof BUILT_IN_ROLES>;

export const PERMISSION_ALIASES: Record<string, string[]> = {
  'manage.organization': [
    'organization.update',
    'organization.read',
    'members.invite',
    'members.update',
    'members.remove',
    'roles.read',
    'roles.assign',
  ],
  'view.organization': ['organization.read'],
  'manage.programs': ['programs.read', 'programs.create', 'programs.update', 'programs.archive'],
  'manage.affiliates': ['affiliates.read', 'affiliates.create', 'affiliates.update', 'affiliates.approve', 'affiliates.suspend'],
  'manage.commissions': ['commissions.read', 'commissions.create', 'commissions.approve', 'commissions.reverse'],
  'manage.payouts': ['payouts.read', 'payouts.create', 'payouts.approve'],
  'manage.api_keys': ['api_keys.read', 'api_keys.create', 'api_keys.revoke'],
  'manage.webhooks': ['webhooks.read', 'webhooks.create', 'webhooks.update', 'webhooks.delete'],
  'view.billing': ['billing.view'],
  'manage.billing': ['billing.view', 'billing.manage', 'billing.subscribe', 'billing.cancel'],
  'manage.billing.coupons': [
    'billing.coupons.read',
    'billing.coupons.create',
    'billing.coupons.update',
    'billing.coupons.activate',
    'billing.coupons.archive',
    'billing.coupons.redemptions.read',
    'billing.coupons.analytics.read',
  ],
  'view.integrations': ['integrations.read', 'integrations.view'],
  'manage.integrations': ['integrations.manage', 'integrations.configure', 'integrations.connect', 'integrations.disconnect', 'integrations.test', 'integrations.sync'],
  'manage.deals': ['deals.view', 'deals.create', 'deals.approve', 'deals.reject', 'deals.edit', 'deals.sync'],
  'view.deals': ['deals.view'],
  'view.programs': ['programs.read'],
  'view.affiliates': ['affiliates.read'],
  'view.conversions': ['conversions.read'],
  'view.payouts': ['payouts.read'],
  'view.fraud': ['fraud.read'],
  'manage.links': ['links.read', 'links.create', 'links.update'],
  'manage.assets': ['assets.view', 'assets.create', 'assets.edit', 'assets.delete', 'assets.publish', 'assets.download'],
  'manage.assetBundles': ['assetBundles.view', 'assetBundles.create', 'assetBundles.edit', 'assetBundles.delete', 'assetBundles.publish'],
  'manage.tiers': ['tiers.view', 'tiers.create', 'tiers.edit', 'tiers.delete', 'tiers.assign'],
  'view.tiers': ['tiers.view'],
  'manage.milestones': ['milestones.view', 'milestones.create', 'milestones.edit', 'milestones.delete'],
  'view.milestones': ['milestones.view'],
  'manage.automations': ['automations.view', 'automations.create', 'automations.edit', 'automations.publish', 'automations.pause', 'automations.delete'],
  'view.automations': ['automations.view'],
  'manage.performance': ['performance.view', 'performance.manage', 'rewards.grant'],
  'view.performance': ['performance.view'],
};
