import { DocumentType, PageSize, PageOrientation, TemplateStatus } from '../../../common/enums';

export interface DocumentVariableDefinition {
  key: string;
  label: string;
  type: 'string' | 'number' | 'currency' | 'date' | 'array' | 'object' | 'badge';
  description?: string;
  defaultValue?: any;
}

export interface DefaultDocumentTemplate {
  key: string;
  name: string;
  category: string;
  documentType: DocumentType;
  description: string;
  pageSize: PageSize;
  orientation: PageOrientation;
  margins: { top: number; right: number; bottom: number; left: number; unit: 'mm' };
  headerSettings: { enabled: boolean; showOn: 'all' | 'first' | 'subsequent'; content?: string };
  footerSettings: { enabled: boolean; showOn: 'all' | 'first' | 'last'; showPageNumber: boolean; format?: string; content?: string };
  watermarkSettings: { enabled: boolean; text?: string; opacity?: number; rotation?: number };
  variables: DocumentVariableDefinition[];
  defaultData: Record<string, any>;
  bodyTemplate: string;
}

export const DEFAULT_DOCUMENT_TEMPLATES: Record<string, DefaultDocumentTemplate> = {
  AFFILIATE_COMMISSION_STATEMENT: {
    key: 'AFFILIATE_COMMISSION_STATEMENT',
    name: 'Affiliate Commission Statement',
    category: 'commissions',
    documentType: DocumentType.COMMISSION_STATEMENT,
    description: 'Official monthly or period statement of earned, pending, and payable affiliate commissions with detailed transaction table.',
    pageSize: PageSize.A4,
    orientation: PageOrientation.PORTRAIT,
    margins: { top: 20, right: 20, bottom: 20, left: 20, unit: 'mm' },
    headerSettings: {
      enabled: true,
      showOn: 'all',
      content: `<div style="display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 16px; border-bottom: 2px solid #0F172A;">
        <div>
          <div style="font-size: 20px; font-weight: 800; color: #0F172A; letter-spacing: -0.5px;">{{organization.name}}</div>
          <div style="font-size: 11px; color: #64748B; margin-top: 2px;">{{organization.supportEmail}} &bull; {{organization.websiteUrl}}</div>
        </div>
        <div style="text-align: right;">
          <div style="font-size: 16px; font-weight: 700; color: #2563EB; text-transform: uppercase; letter-spacing: 0.5px;">Commission Statement</div>
          <div style="font-size: 12px; font-weight: 600; color: #334155; margin-top: 2px;">Statement #: {{statement.number}}</div>
          <div style="font-size: 11px; color: #64748B;">Date: {{statement.date}}</div>
        </div>
      </div>`,
    },
    footerSettings: {
      enabled: true,
      showOn: 'all',
      showPageNumber: true,
      format: 'Page {{pageNumber}} of {{totalPages}}',
      content: `<div style="display: flex; justify-content: space-between; align-items: center; padding-top: 12px; border-top: 1px solid #E2E8F0; font-size: 10px; color: #94A3B8;">
        <div>{{organization.name}} &bull; Confidential Financial Statement</div>
        <div>Page {{pageNumber}} of {{totalPages}}</div>
        <div>Generated by PartnerIQ &bull; {{printDate}}</div>
      </div>`,
    },
    watermarkSettings: { enabled: false, text: 'CONFIDENTIAL', opacity: 0.08, rotation: -35 },
    variables: [
      { key: 'organization.name', label: 'Organization Name', type: 'string', defaultValue: 'PartnerIQ Technologies' },
      { key: 'organization.supportEmail', label: 'Support Email', type: 'string', defaultValue: 'info@partneriq.in' },
      { key: 'organization.websiteUrl', label: 'Website', type: 'string', defaultValue: 'https://partneriq.in' },
      { key: 'affiliate.name', label: 'Affiliate Name', type: 'string', defaultValue: 'Sarah Jenkins' },
      { key: 'affiliate.email', label: 'Affiliate Email', type: 'string', defaultValue: 'sarah.j@creators.network' },
      { key: 'affiliate.code', label: 'Affiliate Code', type: 'string', defaultValue: 'CREATOR-SJ89' },
      { key: 'statement.number', label: 'Statement Number', type: 'string', defaultValue: 'CS-2026-000124' },
      { key: 'statement.date', label: 'Statement Date', type: 'string', defaultValue: '05 Sep 2026' },
      { key: 'statement.period', label: 'Period', type: 'string', defaultValue: '01 Aug 2026 - 31 Aug 2026' },
      { key: 'statement.currency', label: 'Currency', type: 'string', defaultValue: 'INR' },
      { key: 'summary.totalEarned', label: 'Total Earned', type: 'currency', defaultValue: 24850 },
      { key: 'summary.pending', label: 'Pending Review', type: 'currency', defaultValue: 4200 },
      { key: 'summary.approved', label: 'Approved', type: 'currency', defaultValue: 8000 },
      { key: 'summary.payable', label: 'Payable Balance', type: 'currency', defaultValue: 12650 },
      { key: 'summary.paidOut', label: 'Already Paid Out', type: 'currency', defaultValue: 0 },
      { key: 'commissions', label: 'Commissions List', type: 'array', defaultValue: [] },
    ],
    defaultData: {
      organization: {
        name: 'Acme SaaS Corp',
        supportEmail: 'billing@acme.com',
        websiteUrl: 'https://acme.com',
      },
      affiliate: {
        name: 'Sarah Jenkins',
        email: 'sarah.j@creators.network',
        code: 'CREATOR-SJ89',
        tier: 'Platinum Partner',
      },
      statement: {
        number: 'CS-2026-000124',
        date: '05 Sep 2026',
        period: '01 Aug 2026 – 31 Aug 2026',
        currency: 'INR',
      },
      summary: {
        totalEarned: 24850,
        pending: 4200,
        approved: 8000,
        payable: 12650,
        paidOut: 0,
      },
      commissions: [
        { date: '2026-08-03', program: 'Creator Pro', conversionRef: 'ORD-98214', revenue: 4999, rate: '20%', amount: 1000, status: 'APPROVED' },
        { date: '2026-08-09', program: 'Enterprise Referral', conversionRef: 'ORD-98305', revenue: 24999, rate: '15%', amount: 3750, status: 'APPROVED' },
        { date: '2026-08-14', program: 'Creator Pro', conversionRef: 'ORD-98441', revenue: 9999, rate: '20%', amount: 2000, status: 'APPROVED' },
        { date: '2026-08-21', program: 'Creator Pro', conversionRef: 'ORD-98512', revenue: 14999, rate: '20%', amount: 3000, status: 'PAYABLE' },
        { date: '2026-08-25', program: 'Enterprise Referral', conversionRef: 'ORD-98604', revenue: 49999, rate: '15%', amount: 7500, status: 'PAYABLE' },
        { date: '2026-08-29', program: 'Creator Pro', conversionRef: 'ORD-98782', revenue: 21000, rate: '20%', amount: 4200, status: 'PENDING' },
      ],
    },
    bodyTemplate: `
<div style="margin-bottom: 24px;">
  <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
    <tr>
      <td style="width: 50%; vertical-align: top; padding-right: 15px;">
        <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B; margin-bottom: 6px;">Affiliate / Partner</div>
        <div style="font-size: 15px; font-weight: 700; color: #0F172A;">{{affiliate.name}}</div>
        <div style="font-size: 12px; color: #475569; margin-top: 2px;">{{affiliate.email}}</div>
        <div style="font-size: 12px; color: #64748B; margin-top: 2px;">Partner ID: <strong>{{affiliate.code}}</strong> &bull; Tier: <span style="background-color: #EEF2FF; color: #4338CA; padding: 2px 6px; border-radius: 4px; font-size: 11px; font-weight: 600;">{{affiliate.tier}}</span></div>
      </td>
      <td style="width: 50%; vertical-align: top; padding-left: 15px;">
        <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B; margin-bottom: 6px;">Statement Period</div>
        <div style="font-size: 14px; font-weight: 600; color: #0F172A;">{{statement.period}}</div>
        <div style="font-size: 12px; color: #64748B; margin-top: 2px;">Base Currency: <strong>{{statement.currency}}</strong></div>
      </td>
    </tr>
  </table>

  <!-- Summary Cards Grid -->
  <table style="width: 100%; border-collapse: separate; border-spacing: 12px 0; margin-bottom: 28px;">
    <tr>
      <td style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 14px; text-align: left; width: 25%;">
        <div style="font-size: 11px; color: #64748B; font-weight: 600; text-transform: uppercase;">Total Earned</div>
        <div style="font-size: 20px; font-weight: 800; color: #0F172A; margin-top: 4px;">{{summary.totalEarned | currency(statement.currency)}}</div>
      </td>
      <td style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 14px; text-align: left; width: 25%;">
        <div style="font-size: 11px; color: #64748B; font-weight: 600; text-transform: uppercase;">Pending Review</div>
        <div style="font-size: 20px; font-weight: 800; color: #D97706; margin-top: 4px;">{{summary.pending | currency(statement.currency)}}</div>
      </td>
      <td style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 14px; text-align: left; width: 25%;">
        <div style="font-size: 11px; color: #64748B; font-weight: 600; text-transform: uppercase;">Approved</div>
        <div style="font-size: 20px; font-weight: 800; color: #2563EB; margin-top: 4px;">{{summary.approved | currency(statement.currency)}}</div>
      </td>
      <td style="background-color: #ECFDF5; border: 1px solid #A7F3D0; border-radius: 8px; padding: 14px; text-align: left; width: 25%;">
        <div style="font-size: 11px; color: #065F46; font-weight: 700; text-transform: uppercase;">Payable Balance</div>
        <div style="font-size: 20px; font-weight: 800; color: #059669; margin-top: 4px;">{{summary.payable | currency(statement.currency)}}</div>
      </td>
    </tr>
  </table>

  <!-- Transactions Header -->
  <div style="font-size: 14px; font-weight: 700; color: #0F172A; margin-bottom: 10px;">Commission Itemized Details</div>

  <!-- Dynamic Repeating Table -->
  <table style="width: 100%; border-collapse: collapse; font-size: 12px; margin-bottom: 24px;">
    <thead>
      <tr style="background-color: #F1F5F9; border-top: 1px solid #CBD5E1; border-bottom: 2px solid #CBD5E1; text-align: left;">
        <th style="padding: 8px 10px; color: #334155; font-weight: 700;">Date</th>
        <th style="padding: 8px 10px; color: #334155; font-weight: 700;">Program</th>
        <th style="padding: 8px 10px; color: #334155; font-weight: 700;">Order Ref</th>
        <th style="padding: 8px 10px; color: #334155; font-weight: 700; text-align: right;">Revenue</th>
        <th style="padding: 8px 10px; color: #334155; font-weight: 700; text-align: center;">Rate</th>
        <th style="padding: 8px 10px; color: #334155; font-weight: 700; text-align: right;">Commission</th>
        <th style="padding: 8px 10px; color: #334155; font-weight: 700; text-align: center;">Status</th>
      </tr>
    </thead>
    <tbody>
      {{#each commissions}}
      <tr style="border-bottom: 1px solid #E2E8F0; page-break-inside: avoid;">
        <td style="padding: 8px 10px; color: #475569;">{{this.date}}</td>
        <td style="padding: 8px 10px; color: #0F172A; font-weight: 600;">{{this.program}}</td>
        <td style="padding: 8px 10px; color: #64748B; font-family: monospace;">{{this.conversionRef}}</td>
        <td style="padding: 8px 10px; color: #334155; text-align: right;">{{this.revenue | currency(statement.currency)}}</td>
        <td style="padding: 8px 10px; color: #475569; text-align: center;">{{this.rate}}</td>
        <td style="padding: 8px 10px; color: #0F172A; font-weight: 700; text-align: right;">{{this.amount | currency(statement.currency)}}</td>
        <td style="padding: 8px 10px; text-align: center;">
          <span style="display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 10px; font-weight: 700; {{#if (eq this.status 'APPROVED')}}background-color: #DBEAFE; color: #1D4ED8;{{else if (eq this.status 'PAYABLE')}}background-color: #D1FAE5; color: #047857;{{else}}background-color: #FEF3C7; color: #B45309;{{/if}}">
            {{this.status}}
          </span>
        </td>
      </tr>
      {{/each}}
    </tbody>
  </table>

  <!-- Terms & Reconciliation Notice -->
  <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 6px; padding: 12px 14px; font-size: 11px; color: #64748B; line-height: 1.5;">
    <strong>Notice:</strong> Commissions marked as <em>PAYABLE</em> are eligible for disbursement in the next scheduled payout cycle according to your partner agreement terms. Any disputed or refunded customer orders are subject to clawback adjustments prior to final settlement.
  </div>
</div>
`,
  },

  AFFILIATE_PAYOUT_STATEMENT: {
    key: 'AFFILIATE_PAYOUT_STATEMENT',
    name: 'Affiliate Payout Statement & Advice',
    category: 'payouts',
    documentType: DocumentType.PAYOUT_STATEMENT,
    description: 'Detailed payout disbursement advice showing gross commissions, adjustments, tax withholding, and net bank settlement.',
    pageSize: PageSize.A4,
    orientation: PageOrientation.PORTRAIT,
    margins: { top: 20, right: 20, bottom: 20, left: 20, unit: 'mm' },
    headerSettings: {
      enabled: true,
      showOn: 'all',
      content: `<div style="display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 16px; border-bottom: 2px solid #0F172A;">
        <div>
          <div style="font-size: 20px; font-weight: 800; color: #0F172A;">{{organization.name}}</div>
          <div style="font-size: 11px; color: #64748B; margin-top: 2px;">Payout & Settlement Advice</div>
        </div>
        <div style="text-align: right;">
          <div style="font-size: 16px; font-weight: 700; color: #059669; text-transform: uppercase;">Payout Receipt</div>
          <div style="font-size: 12px; font-weight: 600; color: #334155; margin-top: 2px;">Ref: {{payout.reference}}</div>
          <div style="font-size: 11px; color: #64748B;">Date: {{payout.date}}</div>
        </div>
      </div>`,
    },
    footerSettings: {
      enabled: true,
      showOn: 'all',
      showPageNumber: true,
      format: 'Page {{pageNumber}} of {{totalPages}}',
      content: `<div style="display: flex; justify-content: space-between; align-items: center; padding-top: 12px; border-top: 1px solid #E2E8F0; font-size: 10px; color: #94A3B8;">
        <div>{{organization.name}} &bull; Settlement Record</div>
        <div>Page {{pageNumber}} of {{totalPages}}</div>
        <div>Processed by PartnerIQ &bull; {{printDate}}</div>
      </div>`,
    },
    watermarkSettings: { enabled: true, text: 'PAID', opacity: 0.07, rotation: -30 },
    variables: [
      { key: 'organization.name', label: 'Organization Name', type: 'string', defaultValue: 'PartnerIQ Global' },
      { key: 'affiliate.name', label: 'Affiliate Name', type: 'string', defaultValue: 'Sarah Jenkins' },
      { key: 'affiliate.email', label: 'Affiliate Email', type: 'string', defaultValue: 'sarah.j@creators.network' },
      { key: 'payout.reference', label: 'Payout Reference', type: 'string', defaultValue: 'PAY-2026-001284' },
      { key: 'payout.date', label: 'Disbursement Date', type: 'string', defaultValue: '05 Sep 2026' },
      { key: 'payout.methodMasked', label: 'Payout Method', type: 'string', defaultValue: 'HDFC Bank •••• 4281' },
      { key: 'payout.currency', label: 'Currency', type: 'string', defaultValue: 'INR' },
      { key: 'payout.grossCommission', label: 'Gross Commission', type: 'currency', defaultValue: 15000 },
      { key: 'payout.adjustments', label: 'Adjustments / Deductions', type: 'currency', defaultValue: -500 },
      { key: 'payout.taxWithholding', label: 'Tax Withheld (TDS/WHT)', type: 'currency', defaultValue: -750 },
      { key: 'payout.netAmount', label: 'Net Disbursed Amount', type: 'currency', defaultValue: 13750 },
      { key: 'payout.status', label: 'Payout Status', type: 'string', defaultValue: 'COMPLETED' },
    ],
    defaultData: {
      organization: {
        name: 'Acme SaaS Corp',
      },
      affiliate: {
        name: 'Sarah Jenkins',
        email: 'sarah.j@creators.network',
        address: 'Suite 402, High Street, Mumbai, MH 400050',
      },
      payout: {
        reference: 'PAY-2026-001284',
        date: '05 Sep 2026',
        methodMasked: 'HDFC Bank •••• 4281 (IMPS / UTR: 6248910248)',
        currency: 'INR',
        grossCommission: 15000,
        adjustments: -500,
        taxWithholding: -750,
        netAmount: 13750,
        status: 'PAID',
      },
    },
    bodyTemplate: `
<div style="margin-bottom: 24px;">
  <!-- Beneficiary and Method Details -->
  <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
    <tr>
      <td style="width: 50%; vertical-align: top; padding-right: 15px;">
        <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B; margin-bottom: 6px;">Beneficiary</div>
        <div style="font-size: 15px; font-weight: 700; color: #0F172A;">{{affiliate.name}}</div>
        <div style="font-size: 12px; color: #475569; margin-top: 2px;">{{affiliate.email}}</div>
        <div style="font-size: 11px; color: #64748B; margin-top: 2px;">{{affiliate.address}}</div>
      </td>
      <td style="width: 50%; vertical-align: top; padding-left: 15px;">
        <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B; margin-bottom: 6px;">Payment Method & Destination</div>
        <div style="font-size: 13px; font-weight: 600; color: #0F172A;">{{payout.methodMasked}}</div>
        <div style="font-size: 12px; color: #64748B; margin-top: 4px;">Status: <span style="display: inline-block; background-color: #D1FAE5; color: #047857; font-weight: 700; font-size: 11px; padding: 2px 8px; border-radius: 4px;">{{payout.status}}</span></div>
      </td>
    </tr>
  </table>

  <!-- Financial Breakdown Table -->
  <div style="font-size: 14px; font-weight: 700; color: #0F172A; margin-bottom: 10px;">Settlement Breakdown</div>

  <table style="width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 24px;">
    <thead>
      <tr style="background-color: #F1F5F9; border-top: 1px solid #CBD5E1; border-bottom: 2px solid #CBD5E1;">
        <th style="padding: 10px 12px; text-align: left; color: #334155; font-weight: 700;">Description</th>
        <th style="padding: 10px 12px; text-align: right; color: #334155; font-weight: 700;">Amount ({{payout.currency}})</th>
      </tr>
    </thead>
    <tbody>
      <tr style="border-bottom: 1px solid #E2E8F0;">
        <td style="padding: 10px 12px; color: #0F172A; font-weight: 600;">Gross Approved Commissions</td>
        <td style="padding: 10px 12px; text-align: right; color: #0F172A; font-weight: 600;">{{payout.grossCommission | currency(payout.currency)}}</td>
      </tr>
      <tr style="border-bottom: 1px solid #E2E8F0;">
        <td style="padding: 10px 12px; color: #64748B;">Adjustment / Refund Deductions</td>
        <td style="padding: 10px 12px; text-align: right; color: #DC2626;">{{payout.adjustments | currency(payout.currency)}}</td>
      </tr>
      <tr style="border-bottom: 1px solid #E2E8F0;">
        <td style="padding: 10px 12px; color: #64748B;">Tax Withholding (WHT / TDS)</td>
        <td style="padding: 10px 12px; text-align: right; color: #DC2626;">{{payout.taxWithholding | currency(payout.currency)}}</td>
      </tr>
      <tr style="background-color: #F8FAFC; border-top: 2px solid #0F172A; border-bottom: 2px solid #0F172A;">
        <td style="padding: 14px 12px; color: #0F172A; font-size: 15px; font-weight: 800;">Net Payout Settled</td>
        <td style="padding: 14px 12px; text-align: right; color: #059669; font-size: 18px; font-weight: 800;">{{payout.netAmount | currency(payout.currency)}}</td>
      </tr>
    </tbody>
  </table>

  <div style="font-size: 11px; color: #94A3B8; text-align: center; margin-top: 30px;">
    This is an electronic settlement advice generated automatically by PartnerIQ. No physical signature is required.
  </div>
</div>
`,
  },

  CUSTOMER_SUBSCRIPTION_INVOICE: {
    key: 'CUSTOMER_SUBSCRIPTION_INVOICE',
    name: 'PartnerIQ Customer Subscription Invoice',
    category: 'billing',
    documentType: DocumentType.INVOICE,
    description: 'Official payment receipt and tax invoice for PartnerIQ platform subscriptions, seat upgrades, and add-on charges sent to customers for download and expense records.',
    pageSize: PageSize.A4,
    orientation: PageOrientation.PORTRAIT,
    margins: { top: 20, right: 20, bottom: 20, left: 20, unit: 'mm' },
    headerSettings: {
      enabled: true,
      showOn: 'all',
      content: `<div style="display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 18px; border-bottom: 2px solid #0F172A;">
        <div>
          <div style="display: flex; align-items: center; gap: 8px;">
            <div style="font-size: 24px; font-weight: 900; color: #0F172A; letter-spacing: -0.5px;">Partner<span style="color: #2563EB;">IQ</span></div>
            <span style="background-color: #D1FAE5; color: #065F46; font-size: 11px; font-weight: 800; padding: 2px 8px; border-radius: 9999px; letter-spacing: 0.5px;">PAID</span>
          </div>
          <div style="font-size: 11px; color: #475569; margin-top: 4px;">{{organization.name}}</div>
          <div style="font-size: 11px; color: #64748B;">{{organization.supportEmail}} &bull; {{organization.websiteUrl}}</div>
          <div style="font-size: 10px; color: #94A3B8; margin-top: 2px;">Tax / EIN: {{organization.taxId}}</div>
        </div>
        <div style="text-align: right;">
          <div style="font-size: 20px; font-weight: 900; color: #0F172A; letter-spacing: 0.5px;">SUBSCRIPTION INVOICE</div>
          <div style="font-size: 13px; font-weight: 700; color: #2563EB; margin-top: 3px;"># {{invoice.number}}</div>
          <div style="font-size: 11px; color: #64748B; margin-top: 2px;">Invoice Date: <strong>{{invoice.date}}</strong></div>
          <div style="font-size: 11px; color: #64748B;">Billing Cycle: {{invoice.billingPeriod}}</div>
        </div>
      </div>`,
    },
    footerSettings: {
      enabled: true,
      showOn: 'all',
      showPageNumber: true,
      format: 'Page {{pageNumber}} of {{totalPages}}',
      content: `<div style="display: flex; justify-content: space-between; align-items: center; padding-top: 14px; border-top: 1px solid #E2E8F0; font-size: 10px; color: #94A3B8;">
        <div>{{organization.name}} &bull; Official Customer Billing Receipt</div>
        <div>Page {{pageNumber}} of {{totalPages}}</div>
        <div>Downloaded via PartnerIQ Billing Portal &bull; {{printDate}}</div>
      </div>`,
    },
    watermarkSettings: { enabled: false, text: 'PAID', opacity: 0.06, rotation: -35 },
    variables: [
      { key: 'organization.name', label: 'Organization Name', type: 'string', defaultValue: 'PartnerIQ Technologies Inc.' },
      { key: 'organization.taxId', label: 'Tax ID / EIN', type: 'string', defaultValue: 'US-EIN 94-3829104' },
      { key: 'organization.address', label: 'PartnerIQ Address', type: 'string', defaultValue: '548 Market St, Suite 39201, San Francisco, CA 94104' },
      { key: 'organization.supportEmail', label: 'Billing Support Email', type: 'string', defaultValue: 'info@partneriq.in' },
      { key: 'organization.websiteUrl', label: 'Website', type: 'string', defaultValue: 'https://partneriq.in' },
      { key: 'customer.name', label: 'Customer Organization', type: 'string', defaultValue: 'Acme Growth Labs' },
      { key: 'customer.contactName', label: 'Contact Person', type: 'string', defaultValue: 'Alex Vance' },
      { key: 'customer.email', label: 'Customer Billing Email', type: 'string', defaultValue: 'billing@acmegrowth.com' },
      { key: 'customer.taxId', label: 'Customer Tax / VAT ID', type: 'string', defaultValue: 'VAT-US92831' },
      { key: 'customer.address', label: 'Customer Billing Address', type: 'string', defaultValue: '100 Montgomery St, Suite 1200, San Francisco, CA 94104' },
      { key: 'invoice.number', label: 'Invoice Number', type: 'string', defaultValue: 'PIQ-INV-2026-0892' },
      { key: 'invoice.date', label: 'Invoice Date', type: 'string', defaultValue: '05 Sep 2026' },
      { key: 'invoice.billingPeriod', label: 'Billing Period', type: 'string', defaultValue: '05 Sep 2026 – 05 Oct 2026' },
      { key: 'invoice.currency', label: 'Currency', type: 'string', defaultValue: 'USD' },
      { key: 'invoice.paymentMethod', label: 'Payment Method', type: 'string', defaultValue: 'Visa ending in 4242 (Stripe)' },
      { key: 'invoice.transactionId', label: 'Payment Reference / Transaction ID', type: 'string', defaultValue: 'ch_3Mtx7aLkdIwHu7ix08Wk7Z3q' },
      { key: 'invoice.paymentDate', label: 'Payment Timestamp', type: 'string', defaultValue: '05 Sep 2026, 12:44 UTC' },
      { key: 'invoice.status', label: 'Payment Status', type: 'string', defaultValue: 'PAID' },
      { key: 'invoice.subtotal', label: 'Subtotal', type: 'currency', defaultValue: 299.00 },
      { key: 'invoice.discount', label: 'Discount Applied', type: 'currency', defaultValue: 0.00 },
      { key: 'invoice.taxAmount', label: 'Tax Amount', type: 'currency', defaultValue: 26.91 },
      { key: 'invoice.taxRate', label: 'Tax Rate', type: 'string', defaultValue: '9%' },
      { key: 'invoice.total', label: 'Total Paid', type: 'currency', defaultValue: 325.91 },
      { key: 'invoice.amountPaid', label: 'Amount Paid', type: 'currency', defaultValue: 325.91 },
      { key: 'invoice.balanceDue', label: 'Balance Due', type: 'currency', defaultValue: 0.00 },
      { key: 'subscription.planName', label: 'Subscription Plan', type: 'string', defaultValue: 'PartnerIQ Growth Plan (Monthly)' },
      { key: 'subscription.nextBillingDate', label: 'Next Renewal Date', type: 'string', defaultValue: '05 Oct 2026' },
      { key: 'items', label: 'Invoice Line Items', type: 'array', defaultValue: [] },
    ],
    defaultData: {
      organization: {
        name: 'PartnerIQ Technologies Inc.',
        taxId: 'US-EIN 94-3829104',
        address: '548 Market St, Suite 39201, San Francisco, CA 94104',
        supportEmail: 'info@partneriq.in',
        websiteUrl: 'https://partneriq.in',
      },
      customer: {
        name: 'Acme Growth Labs LLC',
        contactName: 'Alex Vance',
        email: 'billing@acmegrowth.com',
        taxId: 'VAT-US92831',
        address: '100 Montgomery St, Suite 1200, San Francisco, CA 94104',
      },
      subscription: {
        planName: 'PartnerIQ Growth Plan (Monthly)',
        nextBillingDate: '05 Oct 2026',
      },
      invoice: {
        number: 'PIQ-INV-2026-0892',
        date: '05 Sep 2026',
        billingPeriod: '05 Sep 2026 – 05 Oct 2026',
        currency: 'USD',
        paymentMethod: 'Visa ending in •••• 4242 (Stripe)',
        transactionId: 'ch_3Mtx7aLkdIwHu7ix08Wk7Z3q',
        paymentDate: '05 Sep 2026, 12:44 UTC',
        status: 'PAID',
        subtotal: 299.00,
        discount: 0.00,
        taxRate: '9%',
        taxAmount: 26.91,
        total: 325.91,
        amountPaid: 325.91,
        balanceDue: 0.00,
      },
      items: [
        {
          description: 'PartnerIQ Growth Plan — Monthly Subscription (Up to 2,500 active affiliates, advanced attribution & fraud shield)',
          qty: 1,
          unitPrice: 249.00,
          total: 249.00,
        },
        {
          description: 'Additional Team Seat License (3 Admin Users)',
          qty: 1,
          unitPrice: 50.00,
          total: 50.00,
        },
      ],
    },
    bodyTemplate: `
<div style="margin-bottom: 24px;">
  <!-- Two Column: Customer Billed To vs Payment Settlement Details -->
  <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
    <tr>
      <td style="width: 50%; vertical-align: top; padding-right: 15px;">
        <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B; letter-spacing: 0.5px; margin-bottom: 6px;">Customer / Billed To</div>
        <div style="font-size: 16px; font-weight: 800; color: #0F172A;">{{customer.name}}</div>
        <div style="font-size: 12px; font-weight: 600; color: #334155; margin-top: 2px;">Attn: {{customer.contactName}} ({{customer.email}})</div>
        <div style="font-size: 11px; color: #64748B; margin-top: 2px; line-height: 1.4;">{{customer.address}}</div>
        {{#if customer.taxId}}
        <div style="font-size: 11px; color: #475569; margin-top: 4px;">Tax / VAT ID: <strong>{{customer.taxId}}</strong></div>
        {{/if}}
      </td>
      <td style="width: 50%; vertical-align: top; padding-left: 15px;">
        <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 14px 16px;">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;">
            <span style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B;">Payment Summary</span>
            <span style="background-color: #D1FAE5; color: #065F46; font-size: 10px; font-weight: 800; padding: 2px 8px; border-radius: 9999px;">PAID IN FULL</span>
          </div>
          <div style="font-size: 12px; color: #334155; margin-top: 4px;"><strong>Method:</strong> {{invoice.paymentMethod}}</div>
          <div style="font-size: 11px; color: #64748B; margin-top: 2px;"><strong>Ref / Txn ID:</strong> <span style="font-family: monospace;">{{invoice.transactionId}}</span></div>
          <div style="font-size: 11px; color: #64748B; margin-top: 2px;"><strong>Paid On:</strong> {{invoice.paymentDate}}</div>
          <div style="font-size: 11px; color: #2563EB; margin-top: 6px; font-weight: 600;">Next Renewal: {{subscription.nextBillingDate}}</div>
        </div>
      </td>
    </tr>
  </table>

  <!-- Items Table -->
  <table style="width: 100%; border-collapse: collapse; font-size: 12px; margin-bottom: 24px;">
    <thead>
      <tr style="background-color: #0F172A; color: #FFFFFF;">
        <th style="padding: 12px 14px; text-align: left; font-weight: 700; border-top-left-radius: 6px;">Description / Subscription Item</th>
        <th style="padding: 12px 14px; text-align: center; font-weight: 700; width: 10%;">Qty</th>
        <th style="padding: 12px 14px; text-align: right; font-weight: 700; width: 18%;">Unit Price</th>
        <th style="padding: 12px 14px; text-align: right; font-weight: 700; width: 18%; border-top-right-radius: 6px;">Total</th>
      </tr>
    </thead>
    <tbody>
      {{#each items}}
      <tr style="border-bottom: 1px solid #E2E8F0;">
        <td style="padding: 12px 14px; color: #0F172A; font-weight: 600; line-height: 1.4;">{{this.description}}</td>
        <td style="padding: 12px 14px; text-align: center; color: #475569;">{{this.qty}}</td>
        <td style="padding: 12px 14px; text-align: right; color: #475569;">{{this.unitPrice | currency(invoice.currency)}}</td>
        <td style="padding: 12px 14px; text-align: right; color: #0F172A; font-weight: 700;">{{this.total | currency(invoice.currency)}}</td>
      </tr>
      {{/each}}
    </tbody>
  </table>

  <!-- Totals Section & Receipt Notes -->
  <table style="width: 100%; border-collapse: collapse; margin-bottom: 28px;">
    <tr>
      <td style="width: 52%; vertical-align: top; padding-right: 20px;">
        <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 14px; font-size: 11px; color: #64748B; line-height: 1.5;">
          <div style="font-size: 12px; font-weight: 700; color: #0F172A; margin-bottom: 4px;">Billing & Tax Information</div>
          Thank you for choosing PartnerIQ. This document serves as your official proof of payment and tax receipt for your accounting and expense records.<br/>
          To manage your subscription, download historical invoices, or update payment cards, visit your organization workspace settings anytime.
        </div>
      </td>
      <td style="width: 48%; vertical-align: top;">
        <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
          <tr>
            <td style="padding: 6px 10px; color: #64748B;">Subtotal</td>
            <td style="padding: 6px 10px; text-align: right; color: #0F172A; font-weight: 600;">{{invoice.subtotal | currency(invoice.currency)}}</td>
          </tr>
          {{#if invoice.discount}}
          <tr>
            <td style="padding: 6px 10px; color: #059669;">Discount Applied</td>
            <td style="padding: 6px 10px; text-align: right; color: #059669; font-weight: 600;">-{{invoice.discount | currency(invoice.currency)}}</td>
          </tr>
          {{/if}}
          <tr>
            <td style="padding: 6px 10px; color: #64748B;">Tax / GST / VAT ({{invoice.taxRate}})</td>
            <td style="padding: 6px 10px; text-align: right; color: #0F172A; font-weight: 600;">{{invoice.taxAmount | currency(invoice.currency)}}</td>
          </tr>
          <tr style="border-top: 2px solid #0F172A; border-bottom: 2px solid #0F172A; background-color: #F8FAFC;">
            <td style="padding: 12px 10px; color: #0F172A; font-size: 14px; font-weight: 800;">Total Paid</td>
            <td style="padding: 12px 10px; text-align: right; color: #059669; font-size: 18px; font-weight: 800;">{{invoice.total | currency(invoice.currency)}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 10px; color: #94A3B8; font-size: 11px;">Amount Due:</td>
            <td style="padding: 6px 10px; text-align: right; color: #059669; font-size: 11px; font-weight: 700;">{{invoice.balanceDue | currency(invoice.currency)}} (Paid)</td>
          </tr>
        </table>
      </td>
    </tr>
  </table>

  <!-- Security & Support Notice -->
  <div style="border-top: 1px dashed #CBD5E1; padding-top: 14px; text-align: center; font-size: 11px; color: #94A3B8;">
    Questions about this invoice? Contact our billing team at <a href="mailto:{{organization.supportEmail}}" style="color: #2563EB; text-decoration: none;">{{organization.supportEmail}}</a> &bull; PartnerIQ Technologies Inc.
  </div>
</div>
`,
  },

  PARTNER_INVOICE: {
    key: 'PARTNER_INVOICE',
    name: 'Partner Tax & Service Invoice',
    category: 'billing',
    documentType: DocumentType.INVOICE,
    description: 'Standard B2B partner invoice with line items breakdown, GST/VAT tax calculation, bank details, and verification QR code.',
    pageSize: PageSize.A4,
    orientation: PageOrientation.PORTRAIT,
    margins: { top: 20, right: 20, bottom: 20, left: 20, unit: 'mm' },
    headerSettings: {
      enabled: true,
      showOn: 'all',
      content: `<div style="display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 16px; border-bottom: 2px solid #0F172A;">
        <div>
          <div style="font-size: 22px; font-weight: 900; color: #0F172A;">{{organization.name}}</div>
          <div style="font-size: 11px; color: #475569; margin-top: 2px;">Tax / GST ID: {{organization.taxId}}</div>
          <div style="font-size: 11px; color: #64748B;">{{organization.address}}</div>
        </div>
        <div style="text-align: right;">
          <div style="font-size: 20px; font-weight: 900; color: #0F172A; letter-spacing: 1px;">TAX INVOICE</div>
          <div style="font-size: 13px; font-weight: 700; color: #2563EB; margin-top: 2px;"># {{invoice.number}}</div>
          <div style="font-size: 11px; color: #64748B; margin-top: 2px;">Invoice Date: {{invoice.date}}</div>
          <div style="font-size: 11px; color: #64748B;">Due Date: {{invoice.dueDate}}</div>
        </div>
      </div>`,
    },
    footerSettings: {
      enabled: true,
      showOn: 'all',
      showPageNumber: true,
      format: 'Page {{pageNumber}} of {{totalPages}}',
      content: `<div style="display: flex; justify-content: space-between; align-items: center; padding-top: 12px; border-top: 1px solid #E2E8F0; font-size: 10px; color: #94A3B8;">
        <div>{{organization.name}} &bull; Official Tax Invoice</div>
        <div>Page {{pageNumber}} of {{totalPages}}</div>
        <div>PartnerIQ Invoice System &bull; {{printDate}}</div>
      </div>`,
    },
    watermarkSettings: { enabled: false, text: 'PAID', opacity: 0.08, rotation: -35 },
    variables: [
      { key: 'organization.name', label: 'Organization Name', type: 'string', defaultValue: 'PartnerIQ Inc.' },
      { key: 'organization.taxId', label: 'Tax ID / GSTIN', type: 'string', defaultValue: 'GSTIN27AABCU9603R1ZM' },
      { key: 'organization.address', label: 'Address', type: 'string', defaultValue: '548 Market St, Suite 39201, San Francisco, CA' },
      { key: 'client.name', label: 'Billed To Client', type: 'string', defaultValue: 'Acme Enterprise Ltd' },
      { key: 'client.taxId', label: 'Client Tax ID', type: 'string', defaultValue: 'GSTIN29AABCP1234F1ZX' },
      { key: 'client.address', label: 'Client Address', type: 'string', defaultValue: '88 MG Road, Bengaluru, KA 560001' },
      { key: 'invoice.number', label: 'Invoice #', type: 'string', defaultValue: 'INV-2026-000123' },
      { key: 'invoice.date', label: 'Date', type: 'string', defaultValue: '05 Sep 2026' },
      { key: 'invoice.dueDate', label: 'Due Date', type: 'string', defaultValue: '20 Sep 2026' },
      { key: 'invoice.currency', label: 'Currency', type: 'string', defaultValue: 'INR' },
      { key: 'invoice.subtotal', label: 'Subtotal', type: 'currency', defaultValue: 4999 },
      { key: 'invoice.taxAmount', label: 'Tax Amount (18% GST)', type: 'currency', defaultValue: 900 },
      { key: 'invoice.total', label: 'Total Amount', type: 'currency', defaultValue: 5899 },
      { key: 'invoice.status', label: 'Payment Status', type: 'string', defaultValue: 'PAID' },
      { key: 'items', label: 'Invoice Line Items', type: 'array', defaultValue: [] },
    ],
    defaultData: {
      organization: {
        name: 'PartnerIQ Technologies Pvt Ltd',
        taxId: '27AABCU9603R1ZM',
        address: 'Level 5, Platina Tower, Bandra Kurla Complex, Mumbai 400051',
      },
      client: {
        name: 'Nexus Partner Growth Group',
        taxId: '29AABCP1234F1ZX',
        address: '4th Floor, Salarpuria Matrix, Koramangala, Bengaluru 560034',
        contactPerson: 'Rahul Sharma',
      },
      invoice: {
        number: 'INV-2026-000123',
        date: '05 Sep 2026',
        dueDate: '20 Sep 2026',
        currency: 'INR',
        subtotal: 4999,
        taxRate: '18%',
        taxAmount: 900,
        total: 5899,
        status: 'PAID',
        qrVerificationUrl: 'https://partneriq.in/verify/inv/INV-2026-000123',
      },
      items: [
        { description: 'PartnerIQ Pro Plan (Annual License - 1 User Seat)', qty: 1, unitPrice: 3999, total: 3999 },
        { description: 'Dedicated Custom Domain & SSL Routing Add-on', qty: 1, unitPrice: 1000, total: 1000 },
      ],
    },
    bodyTemplate: `
<div style="margin-bottom: 24px;">
  <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
    <tr>
      <td style="width: 50%; vertical-align: top; padding-right: 15px;">
        <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B; margin-bottom: 6px;">Billed To (Customer)</div>
        <div style="font-size: 15px; font-weight: 700; color: #0F172A;">{{client.name}}</div>
        <div style="font-size: 12px; color: #475569; margin-top: 2px;">Attn: {{client.contactPerson}}</div>
        <div style="font-size: 11px; color: #64748B; margin-top: 2px;">{{client.address}}</div>
        <div style="font-size: 11px; color: #64748B; margin-top: 2px;">GST / Tax ID: <strong>{{client.taxId}}</strong></div>
      </td>
      <td style="width: 50%; vertical-align: top; padding-left: 15px; text-align: right;">
        <div style="display: inline-block; text-align: left; background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 12px 16px;">
          <div style="font-size: 11px; color: #64748B; font-weight: 600;">Payment Status</div>
          <div style="font-size: 16px; font-weight: 800; color: #059669; margin-top: 2px;">PAID &bull; SETTLED</div>
          <div style="font-size: 11px; color: #64748B; margin-top: 4px;">Paid via Razorpay / Stripe</div>
        </div>
      </td>
    </tr>
  </table>

  <!-- Items Table -->
  <table style="width: 100%; border-collapse: collapse; font-size: 12px; margin-bottom: 20px;">
    <thead>
      <tr style="background-color: #0F172A; color: #FFFFFF;">
        <th style="padding: 10px 12px; text-align: left; font-weight: 700; width: 60%;">Description</th>
        <th style="padding: 10px 12px; text-align: center; font-weight: 700; width: 10%;">Qty</th>
        <th style="padding: 10px 12px; text-align: right; font-weight: 700; width: 15%;">Unit Price</th>
        <th style="padding: 10px 12px; text-align: right; font-weight: 700; width: 15%;">Total</th>
      </tr>
    </thead>
    <tbody>
      {{#each items}}
      <tr style="border-bottom: 1px solid #E2E8F0;">
        <td style="padding: 10px 12px; color: #0F172A; font-weight: 500;">{{this.description}}</td>
        <td style="padding: 10px 12px; text-align: center; color: #475569;">{{this.qty}}</td>
        <td style="padding: 10px 12px; text-align: right; color: #475569;">{{this.unitPrice | currency(invoice.currency)}}</td>
        <td style="padding: 10px 12px; text-align: right; color: #0F172A; font-weight: 700;">{{this.total | currency(invoice.currency)}}</td>
      </tr>
      {{/each}}
    </tbody>
  </table>

  <!-- Totals Section -->
  <table style="width: 100%; border-collapse: collapse; margin-bottom: 28px;">
    <tr>
      <td style="width: 55%; vertical-align: top; padding-right: 20px;">
        <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 6px; padding: 12px; font-size: 11px; color: #64748B;">
          <strong>Authorized Signatory & Verification</strong><br/>
          Digitally signed by PartnerIQ Financial Engine.<br/>
          Verify invoice authenticity at: <a href="{{invoice.qrVerificationUrl}}" style="color: #2563EB;">partneriq.in/verify</a>
        </div>
      </td>
      <td style="width: 45%; vertical-align: top;">
        <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
          <tr>
            <td style="padding: 6px 8px; color: #64748B;">Subtotal</td>
            <td style="padding: 6px 8px; text-align: right; color: #0F172A; font-weight: 600;">{{invoice.subtotal | currency(invoice.currency)}}</td>
          </tr>
          <tr>
            <td style="padding: 6px 8px; color: #64748B;">GST / Tax ({{invoice.taxRate}})</td>
            <td style="padding: 6px 8px; text-align: right; color: #0F172A; font-weight: 600;">{{invoice.taxAmount | currency(invoice.currency)}}</td>
          </tr>
          <tr style="border-top: 2px solid #0F172A; border-bottom: 2px solid #0F172A; background-color: #F8FAFC;">
            <td style="padding: 10px 8px; color: #0F172A; font-size: 14px; font-weight: 800;">Grand Total</td>
            <td style="padding: 10px 8px; text-align: right; color: #2563EB; font-size: 16px; font-weight: 800;">{{invoice.total | currency(invoice.currency)}}</td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</div>
`,
  },

  AFFILIATE_AGREEMENT: {
    key: 'AFFILIATE_AGREEMENT',
    name: 'Affiliate & Partner Agreement',
    category: 'affiliates',
    documentType: DocumentType.AFFILIATE_AGREEMENT,
    description: 'Formal binding partner contract covering commission terms, non-disclosure, intellectual property, and signature block.',
    pageSize: PageSize.A4,
    orientation: PageOrientation.PORTRAIT,
    margins: { top: 22, right: 22, bottom: 22, left: 22, unit: 'mm' },
    headerSettings: {
      enabled: true,
      showOn: 'all',
      content: `<div style="display: flex; justify-content: space-between; align-items: center; padding-bottom: 14px; border-bottom: 1px solid #CBD5E1;">
        <div style="font-size: 14px; font-weight: 800; color: #0F172A;">{{organization.name}} &bull; Partner Terms</div>
        <div style="font-size: 11px; color: #64748B;">Agreement Code: <strong>{{agreement.code}}</strong></div>
      </div>`,
    },
    footerSettings: {
      enabled: true,
      showOn: 'all',
      showPageNumber: true,
      format: 'Page {{pageNumber}} of {{totalPages}}',
      content: `<div style="display: flex; justify-content: space-between; align-items: center; padding-top: 10px; border-top: 1px solid #E2E8F0; font-size: 10px; color: #94A3B8;">
        <div>Confidential &bull; {{organization.name}} & {{affiliate.name}}</div>
        <div>Page {{pageNumber}} of {{totalPages}}</div>
      </div>`,
    },
    watermarkSettings: { enabled: false, text: '', opacity: 0.05, rotation: -30 },
    variables: [
      { key: 'organization.name', label: 'Company / Brand Name', type: 'string', defaultValue: 'PartnerIQ Inc.' },
      { key: 'affiliate.name', label: 'Partner Full Name', type: 'string', defaultValue: 'Sarah Jenkins' },
      { key: 'affiliate.company', label: 'Partner Entity / Business', type: 'string', defaultValue: 'SJ Media Group' },
      { key: 'agreement.code', label: 'Agreement Code', type: 'string', defaultValue: 'AGR-2026-9912' },
      { key: 'agreement.effectiveDate', label: 'Effective Date', type: 'string', defaultValue: '01 Sep 2026' },
      { key: 'agreement.commissionRate', label: 'Commission Rate', type: 'string', defaultValue: '20% Recurring' },
      { key: 'agreement.payoutSchedule', label: 'Payout Schedule', type: 'string', defaultValue: 'Net-30 Monthly' },
    ],
    defaultData: {
      organization: {
        name: 'Acme Technologies Inc.',
        representative: 'David Chen, Head of Growth',
      },
      affiliate: {
        name: 'Sarah Jenkins',
        company: 'SJ Media Group LLC',
        email: 'sarah.j@creators.network',
      },
      agreement: {
        code: 'AGR-2026-9912',
        effectiveDate: '01 Sep 2026',
        commissionRate: '20% recurring monthly on active subscriptions',
        payoutSchedule: 'Net 30 days after month end, threshold $100',
      },
    },
    bodyTemplate: `
<div style="font-family: serif; color: #0F172A; line-height: 1.7; font-size: 12.5px;">
  <div style="text-align: center; margin-bottom: 24px;">
    <h1 style="font-family: sans-serif; font-size: 20px; font-weight: 800; margin: 0 0 6px 0; color: #0F172A; text-transform: uppercase; letter-spacing: 0.5px;">AFFILIATE PARTNERSHIP AGREEMENT</h1>
    <div style="font-size: 12px; color: #64748B;">Effective as of: <strong>{{agreement.effectiveDate}}</strong></div>
  </div>

  <p>This Affiliate Agreement (the "Agreement") is entered into between <strong>{{organization.name}}</strong> ("Company"), and <strong>{{affiliate.name}}</strong> / <strong>{{affiliate.company}}</strong> ("Affiliate").</p>

  <h3 style="font-family: sans-serif; font-size: 13px; font-weight: 700; color: #0F172A; margin: 16px 0 6px 0; text-transform: uppercase;">1. Appointment & Referral Promotion</h3>
  <p>The Company engages the Affiliate as a non-exclusive partner to promote and refer qualified customers to Company services using designated tracking links provided through PartnerIQ.</p>

  <h3 style="font-family: sans-serif; font-size: 13px; font-weight: 700; color: #0F172A; margin: 16px 0 6px 0; text-transform: uppercase;">2. Commission & Payment Terms</h3>
  <p>The Affiliate is eligible to earn commissions under the following structure:</p>
  <ul style="margin: 6px 0; padding-left: 20px;">
    <li><strong>Commission Rate:</strong> {{agreement.commissionRate}}</li>
    <li><strong>Disbursement Terms:</strong> {{agreement.payoutSchedule}}</li>
    <li><strong>Attribution:</strong> Verified first-party click tracking via PartnerIQ Attribution Engine</li>
  </ul>

  <h3 style="font-family: sans-serif; font-size: 13px; font-weight: 700; color: #0F172A; margin: 16px 0 6px 0; text-transform: uppercase;">3. Ethical Marketing & Compliance</h3>
  <p>Affiliate agrees not to engage in spamming, deceptive marketing, bidding on trademarked keywords without authorization, or generating fraudulent conversions.</p>

  <!-- Visual Signature Block (Print-Safe) -->
  <div style="margin-top: 40px; page-break-inside: avoid;">
    <table style="width: 100%; border-collapse: collapse; font-family: sans-serif;">
      <tr>
        <td style="width: 48%; vertical-align: top; border-top: 1.5px solid #0F172A; padding-top: 10px;">
          <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B;">For Company</div>
          <div style="font-size: 13px; font-weight: 700; color: #0F172A; margin-top: 6px;">{{organization.name}}</div>
          <div style="font-size: 12px; color: #475569;">{{organization.representative}}</div>
          <div style="font-size: 11px; color: #64748B; margin-top: 6px;">Date: {{agreement.effectiveDate}}</div>
        </td>
        <td style="width: 4%;"></td>
        <td style="width: 48%; vertical-align: top; border-top: 1.5px solid #0F172A; padding-top: 10px;">
          <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; color: #64748B;">For Affiliate / Partner</div>
          <div style="font-size: 13px; font-weight: 700; color: #0F172A; margin-top: 6px;">{{affiliate.name}}</div>
          <div style="font-size: 12px; color: #475569;">{{affiliate.company}}</div>
          <div style="font-size: 11px; color: #64748B; margin-top: 6px;">Date: {{agreement.effectiveDate}}</div>
        </td>
      </tr>
    </table>
  </div>
</div>
`,
  },

  PARTNER_CERTIFICATE: {
    key: 'PARTNER_CERTIFICATE',
    name: 'Top Partner Performance Certificate',
    category: 'reports',
    documentType: DocumentType.CERTIFICATE,
    description: 'Landscape orientation recognition certificate awarded to high-performing affiliates and tier achievers.',
    pageSize: PageSize.A4,
    orientation: PageOrientation.LANDSCAPE,
    margins: { top: 18, right: 18, bottom: 18, left: 18, unit: 'mm' },
    headerSettings: { enabled: false, showOn: 'first' },
    footerSettings: {
      enabled: true,
      showOn: 'first',
      showPageNumber: false,
      content: `<div style="text-align: center; font-size: 10px; color: #94A3B8;">Certified by PartnerIQ Trust & Verification Network &bull; Certificate ID: {{certificate.id}}</div>`,
    },
    watermarkSettings: { enabled: false, text: '', opacity: 0.05, rotation: 0 },
    variables: [
      { key: 'organization.name', label: 'Company Name', type: 'string', defaultValue: 'PartnerIQ Inc.' },
      { key: 'affiliate.name', label: 'Affiliate Full Name', type: 'string', defaultValue: 'Sarah Jenkins' },
      { key: 'certificate.title', label: 'Award Title', type: 'string', defaultValue: 'Premier Diamond Partner of the Year' },
      { key: 'certificate.date', label: 'Award Date', type: 'string', defaultValue: 'September 2026' },
      { key: 'certificate.id', label: 'Certificate ID', type: 'string', defaultValue: 'CERT-2026-DIAMOND-042' },
    ],
    defaultData: {
      organization: {
        name: 'PartnerIQ Global Ecosystem',
      },
      affiliate: {
        name: 'Sarah Jenkins',
      },
      certificate: {
        title: 'Premier Diamond Partner of the Year',
        date: 'September 2026',
        id: 'CERT-2026-DIAMOND-042',
      },
    },
    bodyTemplate: `
<div style="border: 6px double #D97706; padding: 36px 40px; text-align: center; background-color: #FFFDF9; border-radius: 4px; box-sizing: border-box;">
  <div style="font-size: 13px; font-weight: 800; text-transform: uppercase; letter-spacing: 3px; color: #B45309; margin-bottom: 12px;">{{organization.name}}</div>
  
  <div style="font-size: 28px; font-weight: 900; color: #1E293B; letter-spacing: -0.5px; margin-bottom: 8px;">CERTIFICATE OF ACHIEVEMENT</div>
  <div style="font-size: 13px; color: #64748B; font-style: italic; margin-bottom: 24px;">This prestigious honor is proudly presented to:</div>
  
  <div style="font-size: 32px; font-weight: 900; color: #0F172A; border-bottom: 2px solid #D97706; display: inline-block; padding: 0 40px 8px 40px; margin-bottom: 20px;">
    {{affiliate.name}}
  </div>
  
  <div style="font-size: 15px; font-weight: 700; color: #D97706; margin-bottom: 10px;">
    {{certificate.title}}
  </div>
  
  <p style="font-size: 12px; color: #475569; max-width: 600px; margin: 0 auto 30px auto; line-height: 1.6;">
    In formal recognition of outstanding performance, exceptional customer conversion volume, and adherence to top partner quality standards in our global affiliate ecosystem.
  </p>
  
  <table style="width: 80%; margin: 0 auto; border-collapse: collapse;">
    <tr>
      <td style="width: 45%; text-align: center; border-top: 1px solid #CBD5E1; padding-top: 8px; font-size: 11px; color: #64748B;">
        <strong>{{certificate.date}}</strong><br/>Date of Conferment
      </td>
      <td style="width: 10%;"></td>
      <td style="width: 45%; text-align: center; border-top: 1px solid #CBD5E1; padding-top: 8px; font-size: 11px; color: #64748B;">
        <strong>Authorized Officer</strong><br/>Partner Operations
      </td>
    </tr>
  </table>
</div>
`,
  },
};

