export enum EnvironmentType {
  TEST = 'TEST',
  LIVE = 'LIVE',
}

export enum SubscriptionStatus {
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  GRACE_PERIOD = 'GRACE_PERIOD',
  RESTRICTED = 'RESTRICTED',
  TRIAL_EXPIRED = 'TRIAL_EXPIRED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED',
  // Backward compatibility aliases
  CREATED = 'CREATED',
  AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING',
  PAUSED = 'PAUSED',
  CANCEL_PENDING = 'CANCEL_PENDING',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}

export enum BillingCycle {
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
  QUARTERLY = 'QUARTERLY',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  LOCKED = 'LOCKED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum PlatformRole {
  USER = 'USER',
  AFFILIATE = 'AFFILIATE',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum IdentityProvider {
  GOOGLE = 'GOOGLE',
  MICROSOFT = 'MICROSOFT',
  GITHUB = 'GITHUB',
  APPLE = 'APPLE',
  SAML = 'SAML',
  OIDC = 'OIDC',
}

export enum OrganizationStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
  CLOSED = 'CLOSED',
}

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  AFFILIATE_MANAGER = 'AFFILIATE_MANAGER',
  FINANCE = 'FINANCE',
  RISK_ANALYST = 'RISK_ANALYST',
  ANALYST = 'ANALYST',
  DEVELOPER = 'DEVELOPER',
  VIEWER = 'VIEWER',
}

export enum ProgramType {
  AFFILIATE = 'AFFILIATE',
  INFLUENCER = 'INFLUENCER',
  REFERRAL = 'REFERRAL',
  AGENCY = 'AGENCY',
  RESELLER = 'RESELLER',
}

export enum ProgramStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
}

export enum CommissionType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  FIXED = 'FIXED_AMOUNT',
  RECURRING_PERCENTAGE = 'RECURRING_PERCENTAGE',
}

export enum AttributionModel {
  FIRST_CLICK = 'FIRST_CLICK',
  LAST_CLICK = 'LAST_CLICK',
  LINEAR = 'LINEAR',
  POSITION_BASED = 'POSITION_BASED',
  TIME_DECAY = 'TIME_DECAY',
  MULTI_TOUCH = 'MULTI_TOUCH',
  CUSTOM = 'CUSTOM',
}

export enum AffiliateStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
}

export enum AffiliateInvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum ApplicationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ConversionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REFUNDED = 'REFUNDED',
  CHARGEBACK = 'CHARGEBACK',
}

export enum FraudStatus {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum FraudReviewStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
}

export enum FraudEntityType {
  CLICK = 'CLICK',
  CONVERSION = 'CONVERSION',
  AFFILIATE = 'AFFILIATE',
  PAYOUT = 'PAYOUT',
}

export enum FraudSignalCategory {
  NETWORK = 'NETWORK',
  DEVICE = 'DEVICE',
  TRAFFIC = 'TRAFFIC',
  BEHAVIOR = 'BEHAVIOR',
  IDENTITY = 'IDENTITY',
  CONVERSION = 'CONVERSION',
  AFFILIATE = 'AFFILIATE',
  PAYMENT = 'PAYMENT',
  PAYOUT = 'PAYOUT',
}

export enum FraudSignalCode {
  IP_REPUTATION = 'IP_REPUTATION',
  IP_VELOCITY = 'IP_VELOCITY',
  AFFILIATE_VELOCITY = 'AFFILIATE_VELOCITY',
  DEVICE_VELOCITY = 'DEVICE_VELOCITY',
  DUPLICATE_DEVICE = 'DUPLICATE_DEVICE',
  GEO_MISMATCH = 'GEO_MISMATCH',
  SELF_REFERRAL = 'SELF_REFERRAL',
  FAST_CONVERSION = 'FAST_CONVERSION',
  DUPLICATE_CONVERSION = 'DUPLICATE_CONVERSION',
  SUSPICIOUS_USER_AGENT = 'SUSPICIOUS_USER_AGENT',
  AMOUNT_ANOMALY = 'AMOUNT_ANOMALY',
  AFFILIATE_LOW_TRUST = 'AFFILIATE_LOW_TRUST',
  AFFILIATE_HIGH_REFUND_RATE = 'AFFILIATE_HIGH_REFUND_RATE',
  AFFILIATE_HIGH_CHARGEBACK_RATE = 'AFFILIATE_HIGH_CHARGEBACK_RATE',
  PAYOUT_AMOUNT_ANOMALY = 'PAYOUT_AMOUNT_ANOMALY',
  PAYOUT_TRUST_DROP = 'PAYOUT_TRUST_DROP',
}

export enum FraudRiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum FraudDecision {
  ALLOW = 'ALLOW',
  REVIEW = 'REVIEW',
  BLOCK = 'BLOCK',
  HOLD = 'HOLD',
}

export enum FraudAssessmentType {
  INITIAL = 'INITIAL',
  REASSESSMENT = 'REASSESSMENT',
  PAYOUT_CHECK = 'PAYOUT_CHECK',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

export enum FraudSensitivity {
  LOW = 'LOW',
  BALANCED = 'BALANCED',
  STRICT = 'STRICT',
  CUSTOM = 'CUSTOM',
}

export enum AffiliateTrustSource {
  AUTOMATED = 'AUTOMATED',
  REASSESSMENT = 'REASSESSMENT',
  MANUAL = 'MANUAL',
}

export enum PayoutStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  PARTIALLY_FAILED = 'PARTIALLY_FAILED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum LedgerEntryType {
  COMMISSION_EARNED = 'COMMISSION_EARNED',
  COMMISSION_APPROVED = 'COMMISSION_APPROVED',
  COMMISSION_REVERSED = 'COMMISSION_REVERSED',
  PAYOUT_CREATED = 'PAYOUT_CREATED',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  GOOGLE_LOGIN_STARTED = 'GOOGLE_LOGIN_STARTED',
  GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS',
  GOOGLE_LOGIN_FAILED = 'GOOGLE_LOGIN_FAILED',
  GOOGLE_ACCOUNT_CREATED = 'GOOGLE_ACCOUNT_CREATED',
  GOOGLE_IDENTITY_LINKED = 'GOOGLE_IDENTITY_LINKED',
  GOOGLE_IDENTITY_UNLINKED = 'GOOGLE_IDENTITY_UNLINKED',
  GOOGLE_LINK_FAILED = 'GOOGLE_LINK_FAILED',
  OAUTH_STATE_REJECTED = 'OAUTH_STATE_REJECTED',
  OAUTH_EMAIL_MISMATCH = 'OAUTH_EMAIL_MISMATCH',
  OAUTH_INVITATION_ACCEPTED = 'OAUTH_INVITATION_ACCEPTED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_ADDED = 'PASSWORD_ADDED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  PROGRAM_CREATED = 'PROGRAM_CREATED',
  PROGRAM_UPDATED = 'PROGRAM_UPDATED',
  AFFILIATE_APPROVED = 'AFFILIATE_APPROVED',
  AFFILIATE_ELIGIBILITY_POLICY_UPDATED = 'AFFILIATE_ELIGIBILITY_POLICY_UPDATED',
  COMMISSION_RULE_CHANGED = 'COMMISSION_RULE_CHANGED',
  COMMISSION_APPROVED = 'COMMISSION_APPROVED',
  COMMISSION_REVERSED = 'COMMISSION_REVERSED',
  PAYOUT_CREATED = 'PAYOUT_CREATED',
  PAYOUT_APPROVED = 'PAYOUT_APPROVED',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  API_KEY_CREATED = 'API_KEY_CREATED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  WEBHOOK_CREATED = 'WEBHOOK_CREATED',
  FRAUD_REVIEW_APPROVED = 'FRAUD_REVIEW_APPROVED',
  FRAUD_REVIEW_REJECTED = 'FRAUD_REVIEW_REJECTED',
  ASSET_CREATED = 'ASSET_CREATED',
  ASSET_UPDATED = 'ASSET_UPDATED',
  ASSET_VERSION_ADDED = 'ASSET_VERSION_ADDED',
  ASSET_ARCHIVED = 'ASSET_ARCHIVED',
  ASSET_DELETED = 'ASSET_DELETED',
  BUNDLE_CREATED = 'BUNDLE_CREATED',
  BUNDLE_UPDATED = 'BUNDLE_UPDATED',
  BUNDLE_PUBLISHED = 'BUNDLE_PUBLISHED',
  BUNDLE_ARCHIVED = 'BUNDLE_ARCHIVED',
  BUNDLE_AUDIENCE_CHANGED = 'BUNDLE_AUDIENCE_CHANGED',
  TIER_CREATED = 'TIER_CREATED',
  TIER_UPDATED = 'TIER_UPDATED',
  TIER_DEACTIVATED = 'TIER_DEACTIVATED',
  TIER_MANUALLY_ASSIGNED = 'TIER_MANUALLY_ASSIGNED',
  TIER_LOCKED = 'TIER_LOCKED',
  TIER_UNLOCKED = 'TIER_UNLOCKED',
  AFFILIATE_TIER_UPGRADED = 'AFFILIATE_TIER_UPGRADED',
  AFFILIATE_TIER_DOWNGRADED = 'AFFILIATE_TIER_DOWNGRADED',
  MILESTONE_CREATED = 'MILESTONE_CREATED',
  MILESTONE_UPDATED = 'MILESTONE_UPDATED',
  MILESTONE_DEACTIVATED = 'MILESTONE_DEACTIVATED',
  MILESTONE_ACHIEVED = 'MILESTONE_ACHIEVED',
  REWARD_GRANTED = 'REWARD_GRANTED',
  AUTOMATION_CREATED = 'AUTOMATION_CREATED',
  AUTOMATION_UPDATED = 'AUTOMATION_UPDATED',
  AUTOMATION_PUBLISHED = 'AUTOMATION_PUBLISHED',
  AUTOMATION_PAUSED = 'AUTOMATION_PAUSED',
  AUTOMATION_ARCHIVED = 'AUTOMATION_ARCHIVED',
  AUTOMATION_EXECUTED = 'AUTOMATION_EXECUTED',
}

export enum AssetType {
  IMAGE = 'IMAGE',
  BANNER = 'BANNER',
  LOGO = 'LOGO',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  PDF = 'PDF',
  BRAND_GUIDELINE = 'BRAND_GUIDELINE',
  EMAIL_TEMPLATE = 'EMAIL_TEMPLATE',
  SOCIAL_COPY = 'SOCIAL_COPY',
  PROMOTIONAL_COPY = 'PROMOTIONAL_COPY',
  CTA = 'CTA',
  PRODUCT_DESCRIPTION = 'PRODUCT_DESCRIPTION',
  LINK = 'LINK',
  QR_CODE = 'QR_CODE',
  COUPON = 'COUPON',
  OTHER = 'OTHER',
}

export enum AssetSourceType {
  FILE = 'FILE',
  TEXT = 'TEXT',
  HTML = 'HTML',
  URL = 'URL',
  GENERATED = 'GENERATED',
}

export enum AssetStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  PROCESSING = 'PROCESSING',
  FAILED = 'FAILED',
}

export enum AssetBundleStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  EXPIRED = 'EXPIRED',
}

export enum AssetBundleVisibility {
  ALL_PROGRAM_AFFILIATES = 'ALL_PROGRAM_AFFILIATES',
  SPECIFIC_AFFILIATES = 'SPECIFIC_AFFILIATES',
  AFFILIATE_SEGMENT = 'AFFILIATE_SEGMENT',
  PARTNER_TIER = 'PARTNER_TIER',
  PRIVATE = 'PRIVATE',
}

export enum AffiliateAssetActivityType {
  VIEW = 'VIEW',
  PREVIEW = 'PREVIEW',
  DOWNLOAD = 'DOWNLOAD',
  COPY = 'COPY',
  LINK_COPY = 'LINK_COPY',
  COUPON_COPY = 'COUPON_COPY',
  QR_DOWNLOAD = 'QR_DOWNLOAD',
}

export enum TrackingLinkStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum WebhookEvent {
  AFFILIATE_CREATED = 'affiliate.created',
  AFFILIATE_APPROVED = 'affiliate.approved',
  CLICK_FLAGGED = 'click.flagged',
  CONVERSION_CREATED = 'conversion.created',
  CONVERSION_APPROVED = 'conversion.approved',
  CONVERSION_REJECTED = 'conversion.rejected',
  CONVERSION_REFUNDED = 'conversion.refunded',
  COMMISSION_CREATED = 'commission.created',
  COMMISSION_APPROVED = 'commission.approved',
  COMMISSION_REVERSED = 'commission.reversed',
  PAYOUT_CREATED = 'payout.created',
  PAYOUT_COMPLETED = 'payout.completed',
  PAYOUT_FAILED = 'payout.failed',
}

export enum IntegrationCategory {
  PAYMENTS = 'PAYMENTS',
  BILLING = 'BILLING',
  COMMERCE = 'COMMERCE',
  CRM = 'CRM',
  AUTOMATION = 'AUTOMATION',
  NOTIFICATIONS = 'NOTIFICATIONS',
  DEVELOPER = 'DEVELOPER',
}

export enum IntegrationStatus {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
  BETA = 'BETA',
  COMING_SOON = 'COMING_SOON',
  DEPRECATED = 'DEPRECATED',
  MAINTENANCE = 'MAINTENANCE',
}

export enum IntegrationConnectionType {
  OAUTH = 'OAUTH',
  API_KEY = 'API_KEY',
  WEBHOOK = 'WEBHOOK',
  NATIVE = 'NATIVE',
  SDK = 'SDK',
}

export enum OrganizationIntegrationStatus {
  NOT_CONNECTED = 'NOT_CONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  DEGRADED = 'DEGRADED',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  PERMISSION_ERROR = 'PERMISSION_ERROR',
  SYNC_ERROR = 'SYNC_ERROR',
  DISCONNECTED = 'DISCONNECTED',
  REVOKED = 'REVOKED',
  ERROR = 'ERROR',
  REAUTH_REQUIRED = 'REAUTH_REQUIRED',
  PENDING = 'PENDING',
}

export enum IntegrationEnvironment {
  TEST = 'TEST',
  LIVE = 'LIVE',
}

export enum IntegrationEventStatus {
  RECEIVED = 'RECEIVED',
  VALIDATED = 'VALIDATED',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  IGNORED = 'IGNORED',
  FAILED = 'FAILED',
  DUPLICATE = 'DUPLICATE',
}

export enum CrmHealthStatus {
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  UNHEALTHY = 'UNHEALTHY',
  UNKNOWN = 'UNKNOWN',
}

export enum PartnerDealStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SYNC_PENDING = 'SYNC_PENDING',
  SYNCED = 'SYNCED',
  QUALIFIED = 'QUALIFIED',
  IN_PROGRESS = 'IN_PROGRESS',
  PROPOSAL = 'PROPOSAL',
  NEGOTIATION = 'NEGOTIATION',
  CLOSED_WON = 'CLOSED_WON',
  CLOSED_LOST = 'CLOSED_LOST',
  CANCELLED = 'CANCELLED',
  SYNC_ERROR = 'SYNC_ERROR',
}

export enum PartnerDealCommissionStatus {
  NOT_ELIGIBLE = 'NOT_ELIGIBLE',
  PENDING = 'PENDING',
  TRIGGERED = 'TRIGGERED',
  REVERSED = 'REVERSED',
}

export enum TierEvaluationPeriod {
  LIFETIME = 'LIFETIME',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
  ROLLING_30_DAYS = 'ROLLING_30_DAYS',
  ROLLING_90_DAYS = 'ROLLING_90_DAYS',
  CUSTOM = 'CUSTOM',
}

export enum TierDowngradeMode {
  NEVER_DOWNGRADE = 'NEVER_DOWNGRADE',
  DOWNGRADE_NEXT_PERIOD = 'DOWNGRADE_NEXT_PERIOD',
  IMMEDIATE_DOWNGRADE = 'IMMEDIATE_DOWNGRADE',
  GRACE_PERIOD = 'GRACE_PERIOD',
}

export enum CommissionRateEffectiveStrategy {
  FUTURE_CONVERSIONS_ONLY = 'FUTURE_CONVERSIONS_ONLY',
  RETROACTIVE_CURRENT_PERIOD = 'RETROACTIVE_CURRENT_PERIOD',
  NEXT_PERIOD = 'NEXT_PERIOD',
  CUSTOM_EFFECTIVE_DATE = 'CUSTOM_EFFECTIVE_DATE',
}

export enum TierTransitionType {
  AUTOMATIC_UPGRADE = 'AUTOMATIC_UPGRADE',
  AUTOMATIC_DOWNGRADE = 'AUTOMATIC_DOWNGRADE',
  MANUAL_OVERRIDE = 'MANUAL_OVERRIDE',
  RESTORE = 'RESTORE',
  INITIAL_ASSIGNMENT = 'INITIAL_ASSIGNMENT',
}

export enum GamificationMetric {
  APPROVED_CONVERSIONS = 'APPROVED_CONVERSIONS',
  REVENUE_GENERATED = 'REVENUE_GENERATED',
  ATTRIBUTED_REVENUE = 'ATTRIBUTED_REVENUE',
  COMMISSION_EARNED = 'COMMISSION_EARNED',
  QUALIFIED_LEADS = 'QUALIFIED_LEADS',
  DEAL_REGISTRATIONS = 'DEAL_REGISTRATIONS',
  CLOSED_WON_DEALS = 'CLOSED_WON_DEALS',
  TRACKING_LINK_CLICKS = 'TRACKING_LINK_CLICKS',
  NEW_CUSTOMERS = 'NEW_CUSTOMERS',
  RECURRING_REVENUE = 'RECURRING_REVENUE',
  CUSTOM_EVENT = 'CUSTOM_EVENT',
}

export enum MilestoneRewardType {
  COMMISSION_RATE_CHANGE = 'COMMISSION_RATE_CHANGE',
  FIXED_BONUS = 'FIXED_BONUS',
  BADGE = 'BADGE',
  TIER_UPGRADE = 'TIER_UPGRADE',
  ACCESS_TO_ASSET_BUNDLE = 'ACCESS_TO_ASSET_BUNDLE',
  EXCLUSIVE_CAMPAIGN_ACCESS = 'EXCLUSIVE_CAMPAIGN_ACCESS',
  COUPON_REWARD = 'COUPON_REWARD',
  NOTIFICATION = 'NOTIFICATION',
  EMAIL = 'EMAIL',
  CUSTOM_REWARD = 'CUSTOM_REWARD',
  MULTI_REWARD = 'MULTI_REWARD',
}

export enum MilestoneResetBehavior {
  NONE = 'NONE',
  RESET_AT_PERIOD_START = 'RESET_AT_PERIOD_START',
  REPEAT_EVERY_N = 'REPEAT_EVERY_N',
}

export enum MilestoneRewardStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum AutomationTriggerType {
  AFFILIATE_REGISTERED = 'AFFILIATE_REGISTERED',
  AFFILIATE_JOINED_PROGRAM = 'AFFILIATE_JOINED_PROGRAM',
  AFFILIATE_APPROVED = 'AFFILIATE_APPROVED',
  AFFILIATE_INVITED = 'AFFILIATE_INVITED',
  AFFILIATE_TIER_CHANGED = 'AFFILIATE_TIER_CHANGED',
  FIRST_TRACKING_LINK_CREATED = 'FIRST_TRACKING_LINK_CREATED',
  FIRST_CLICK_RECEIVED = 'FIRST_CLICK_RECEIVED',
  FIRST_CONVERSION = 'FIRST_CONVERSION',
  TRACKING_LINK_CREATED = 'FIRST_TRACKING_LINK_CREATED',
  APPROVED_CONVERSION = 'CONVERSION_APPROVED',
  CONVERSION_APPROVED = 'CONVERSION_APPROVED',
  MILESTONE_REACHED = 'MILESTONE_REACHED',
  TIER_UPGRADED = 'TIER_UPGRADED',
  TIER_DOWNGRADED = 'TIER_DOWNGRADED',
  AFFILIATE_INACTIVE = 'AFFILIATE_INACTIVE',
  PERFORMANCE_THRESHOLD_REACHED = 'PERFORMANCE_THRESHOLD_REACHED',
  DEAL_REGISTERED = 'DEAL_REGISTERED',
  DEAL_CLOSED_WON = 'DEAL_CLOSED_WON',
  CUSTOM_EVENT = 'CUSTOM_EVENT',
}

export enum AutomationWorkflowStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
}

export enum AutomationNodeType {
  TRIGGER = 'TRIGGER',
  DELAY = 'DELAY',
  CONDITION = 'CONDITION',
  ACTION = 'ACTION',
  BRANCH = 'BRANCH',
  GOAL = 'GOAL',
  END = 'END',
}

export enum AutomationActionType {
  SEND_EMAIL = 'SEND_EMAIL',
  SEND_IN_APP_NOTIFICATION = 'SEND_IN_APP_NOTIFICATION',
  ASSIGN_TIER = 'ASSIGN_TIER',
  AWARD_BADGE = 'AWARD_BADGE',
  CHANGE_COMMISSION_RATE = 'CHANGE_COMMISSION_RATE',
  GRANT_BONUS = 'GRANT_BONUS',
  UNLOCK_ASSET_BUNDLE = 'UNLOCK_ASSET_BUNDLE',
  ADD_TAG = 'ADD_TAG',
  REMOVE_TAG = 'REMOVE_TAG',
  NOTIFY_ORGANIZATION_ADMIN = 'NOTIFY_ORGANIZATION_ADMIN',
  WEBHOOK = 'WEBHOOK',
}

export enum AutomationExecutionStatus {
  RUNNING = 'RUNNING',
  WAITING = 'WAITING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  GOAL_REACHED = 'GOAL_REACHED',
}

export enum AutomationStepStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum AutomationEmailDeliveryStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  BOUNCED = 'BOUNCED',
  FAILED = 'FAILED',
  OPENED = 'OPENED',
  CLICKED = 'CLICKED',
}

export enum SecurityEventType {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  MFA_CHALLENGE_CREATED = 'MFA_CHALLENGE_CREATED',
  MFA_SUCCESS = 'MFA_SUCCESS',
  MFA_FAILED = 'MFA_FAILED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',
  RECOVERY_CODE_USED = 'RECOVERY_CODE_USED',
  RECOVERY_CODES_GENERATED = 'RECOVERY_CODES_GENERATED',
  NEW_DEVICE_LOGIN = 'NEW_DEVICE_LOGIN',
  TRUSTED_DEVICE_ADDED = 'TRUSTED_DEVICE_ADDED',
  TRUSTED_DEVICE_REMOVED = 'TRUSTED_DEVICE_REMOVED',
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL = 'LOGOUT_ALL',
  LOGOUT_OTHERS = 'LOGOUT_OTHERS',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_CHANGED = 'EMAIL_CHANGED',
  REFRESH_TOKEN_ROTATED = 'REFRESH_TOKEN_ROTATED',
  REFRESH_TOKEN_REUSE_DETECTED = 'REFRESH_TOKEN_REUSE_DETECTED',
  STEP_UP_CHALLENGE_CREATED = 'STEP_UP_CHALLENGE_CREATED',
  STEP_UP_VERIFIED = 'STEP_UP_VERIFIED',
  STEP_UP_FAILED = 'STEP_UP_FAILED',
  ORGANIZATION_MFA_REQUIRED = 'ORGANIZATION_MFA_REQUIRED',
  ORGANIZATION_SECURITY_POLICY_CHANGED = 'ORGANIZATION_SECURITY_POLICY_CHANGED',
  API_KEY_CREATED = 'API_KEY_CREATED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  PAYMENT_CONFIGURATION_CHANGED = 'PAYMENT_CONFIGURATION_CHANGED',
  SUSPICIOUS_LOGIN = 'SUSPICIOUS_LOGIN',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AuthLevel {
  PASSWORD = 'PASSWORD',
  MFA = 'MFA',
}

export enum TemplateChannel {
  EMAIL = 'EMAIL',
  DOCUMENT = 'DOCUMENT',
}

export enum DocumentType {
  INVOICE = 'INVOICE',
  COMMISSION_STATEMENT = 'COMMISSION_STATEMENT',
  PAYOUT_STATEMENT = 'PAYOUT_STATEMENT',
  AFFILIATE_AGREEMENT = 'AFFILIATE_AGREEMENT',
  PARTNER_AGREEMENT = 'PARTNER_AGREEMENT',
  TAX_STATEMENT = 'TAX_STATEMENT',
  CERTIFICATE = 'CERTIFICATE',
  RECEIPT = 'RECEIPT',
  REPORT = 'REPORT',
  CUSTOM = 'CUSTOM',
}

export enum DocumentStatus {
  DRAFT = 'DRAFT',
  QUEUED = 'QUEUED',
  GENERATING = 'GENERATING',
  GENERATED = 'GENERATED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}

export enum TemplateStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum PageSize {
  A4 = 'A4',
  LETTER = 'LETTER',
  LEGAL = 'LEGAL',
  CUSTOM = 'CUSTOM',
}

export enum PageOrientation {
  PORTRAIT = 'PORTRAIT',
  LANDSCAPE = 'LANDSCAPE',
}
