export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  LOCKED = 'LOCKED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum PlatformRole {
  USER = 'USER',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum OrganizationStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
  CLOSED = 'CLOSED',
}

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  AFFILIATE_MANAGER = 'AFFILIATE_MANAGER',
  FINANCE = 'FINANCE',
  RISK_ANALYST = 'RISK_ANALYST',
  ANALYST = 'ANALYST',
  DEVELOPER = 'DEVELOPER',
  VIEWER = 'VIEWER',
}

export enum ProgramType {
  AFFILIATE = 'AFFILIATE',
  INFLUENCER = 'INFLUENCER',
  REFERRAL = 'REFERRAL',
  AGENCY = 'AGENCY',
  RESELLER = 'RESELLER',
}

export enum ProgramStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
}

export enum CommissionType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  RECURRING_PERCENTAGE = 'RECURRING_PERCENTAGE',
}

export enum AttributionModel {
  FIRST_CLICK = 'FIRST_CLICK',
  LAST_CLICK = 'LAST_CLICK',
}

export enum AffiliateStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
}

export enum ApplicationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ConversionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REFUNDED = 'REFUNDED',
  CHARGEBACK = 'CHARGEBACK',
}

export enum FraudStatus {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum FraudReviewStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
}

export enum FraudEntityType {
  CLICK = 'CLICK',
  CONVERSION = 'CONVERSION',
  AFFILIATE = 'AFFILIATE',
  PAYOUT = 'PAYOUT',
}

export enum FraudSignalCategory {
  NETWORK = 'NETWORK',
  DEVICE = 'DEVICE',
  TRAFFIC = 'TRAFFIC',
  BEHAVIOR = 'BEHAVIOR',
  IDENTITY = 'IDENTITY',
  CONVERSION = 'CONVERSION',
  AFFILIATE = 'AFFILIATE',
  PAYMENT = 'PAYMENT',
  PAYOUT = 'PAYOUT',
}

export enum FraudSignalCode {
  IP_REPUTATION = 'IP_REPUTATION',
  IP_VELOCITY = 'IP_VELOCITY',
  AFFILIATE_VELOCITY = 'AFFILIATE_VELOCITY',
  DEVICE_VELOCITY = 'DEVICE_VELOCITY',
  DUPLICATE_DEVICE = 'DUPLICATE_DEVICE',
  GEO_MISMATCH = 'GEO_MISMATCH',
  SELF_REFERRAL = 'SELF_REFERRAL',
  FAST_CONVERSION = 'FAST_CONVERSION',
  DUPLICATE_CONVERSION = 'DUPLICATE_CONVERSION',
  SUSPICIOUS_USER_AGENT = 'SUSPICIOUS_USER_AGENT',
  AMOUNT_ANOMALY = 'AMOUNT_ANOMALY',
  AFFILIATE_LOW_TRUST = 'AFFILIATE_LOW_TRUST',
  AFFILIATE_HIGH_REFUND_RATE = 'AFFILIATE_HIGH_REFUND_RATE',
  AFFILIATE_HIGH_CHARGEBACK_RATE = 'AFFILIATE_HIGH_CHARGEBACK_RATE',
  PAYOUT_AMOUNT_ANOMALY = 'PAYOUT_AMOUNT_ANOMALY',
  PAYOUT_TRUST_DROP = 'PAYOUT_TRUST_DROP',
}

export enum FraudRiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum FraudDecision {
  ALLOW = 'ALLOW',
  REVIEW = 'REVIEW',
  BLOCK = 'BLOCK',
  HOLD = 'HOLD',
}

export enum FraudAssessmentType {
  INITIAL = 'INITIAL',
  REASSESSMENT = 'REASSESSMENT',
  PAYOUT_CHECK = 'PAYOUT_CHECK',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

export enum FraudSensitivity {
  LOW = 'LOW',
  BALANCED = 'BALANCED',
  STRICT = 'STRICT',
  CUSTOM = 'CUSTOM',
}

export enum AffiliateTrustSource {
  AUTOMATED = 'AUTOMATED',
  REASSESSMENT = 'REASSESSMENT',
  MANUAL = 'MANUAL',
}

export enum PayoutStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  PARTIALLY_FAILED = 'PARTIALLY_FAILED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum LedgerEntryType {
  COMMISSION_EARNED = 'COMMISSION_EARNED',
  COMMISSION_APPROVED = 'COMMISSION_APPROVED',
  COMMISSION_REVERSED = 'COMMISSION_REVERSED',
  PAYOUT_CREATED = 'PAYOUT_CREATED',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  PROGRAM_CREATED = 'PROGRAM_CREATED',
  PROGRAM_UPDATED = 'PROGRAM_UPDATED',
  AFFILIATE_APPROVED = 'AFFILIATE_APPROVED',
  COMMISSION_RULE_CHANGED = 'COMMISSION_RULE_CHANGED',
  COMMISSION_APPROVED = 'COMMISSION_APPROVED',
  COMMISSION_REVERSED = 'COMMISSION_REVERSED',
  PAYOUT_CREATED = 'PAYOUT_CREATED',
  PAYOUT_APPROVED = 'PAYOUT_APPROVED',
  API_KEY_CREATED = 'API_KEY_CREATED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  WEBHOOK_CREATED = 'WEBHOOK_CREATED',
  FRAUD_REVIEW_APPROVED = 'FRAUD_REVIEW_APPROVED',
  FRAUD_REVIEW_REJECTED = 'FRAUD_REVIEW_REJECTED',
}

export enum TrackingLinkStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum WebhookEvent {
  AFFILIATE_CREATED = 'affiliate.created',
  AFFILIATE_APPROVED = 'affiliate.approved',
  CLICK_FLAGGED = 'click.flagged',
  CONVERSION_CREATED = 'conversion.created',
  CONVERSION_APPROVED = 'conversion.approved',
  CONVERSION_REJECTED = 'conversion.rejected',
  CONVERSION_REFUNDED = 'conversion.refunded',
  COMMISSION_CREATED = 'commission.created',
  COMMISSION_APPROVED = 'commission.approved',
  COMMISSION_REVERSED = 'commission.reversed',
  PAYOUT_CREATED = 'payout.created',
  PAYOUT_COMPLETED = 'payout.completed',
  PAYOUT_FAILED = 'payout.failed',
}

export enum IntegrationCategory {
  PAYMENTS = 'PAYMENTS',
  BILLING = 'BILLING',
  COMMERCE = 'COMMERCE',
  CRM = 'CRM',
  AUTOMATION = 'AUTOMATION',
  NOTIFICATIONS = 'NOTIFICATIONS',
  DEVELOPER = 'DEVELOPER',
}

export enum IntegrationStatus {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
  BETA = 'BETA',
  COMING_SOON = 'COMING_SOON',
  DEPRECATED = 'DEPRECATED',
  MAINTENANCE = 'MAINTENANCE',
}

export enum IntegrationConnectionType {
  OAUTH = 'OAUTH',
  API_KEY = 'API_KEY',
  WEBHOOK = 'WEBHOOK',
  NATIVE = 'NATIVE',
  SDK = 'SDK',
}

export enum OrganizationIntegrationStatus {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
  REAUTH_REQUIRED = 'REAUTH_REQUIRED',
  PENDING = 'PENDING',
}

export enum IntegrationEnvironment {
  TEST = 'TEST',
  LIVE = 'LIVE',
}

export enum IntegrationEventStatus {
  RECEIVED = 'RECEIVED',
  VALIDATED = 'VALIDATED',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  IGNORED = 'IGNORED',
  FAILED = 'FAILED',
  DUPLICATE = 'DUPLICATE',
}
