export enum RoleType {
  SYSTEM = 'SYSTEM',
  CUSTOM = 'CUSTOM',
}

export enum MembershipStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REMOVED = 'REMOVED',
}

export enum ProgramAccessType {
  ALL = 'ALL',
  SELECTED = 'SELECTED',
}

export enum PolicyEffect {
  ALLOW = 'ALLOW',
  DENY = 'DENY',
  REQUIRE_HIGHER_APPROVAL = 'REQUIRE_HIGHER_APPROVAL',
}

export enum AuditActionExt {
  MEMBER_INVITED = 'MEMBER_INVITED',
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
  POLICY_CREATED = 'POLICY_CREATED',
  POLICY_UPDATED = 'POLICY_UPDATED',
  POLICY_DELETED = 'POLICY_DELETED',
  OWNERSHIP_TRANSFERRED = 'OWNERSHIP_TRANSFERRED',
}
